export enum DomainEventType {
  HOST_ONBOARDING_STARTED = 'HOST_ONBOARDING_STARTED',
  HOST_ONBOARDING_COMPLETED = 'HOST_ONBOARDING_COMPLETED',
  LISTING_CREATED = 'LISTING_CREATED',
  LISTING_PUBLISHED = 'LISTING_PUBLISHED',
  LISTING_DELETED = 'LISTING_DELETED',
  BOOKING_REQUESTED = 'BOOKING_REQUESTED',
  BOOKING_APPROVED = 'BOOKING_APPROVED',
  BOOKING_REJECTED = 'BOOKING_REJECTED',
  STAY_STARTED = 'STAY_STARTED',
  STAY_ENDED = 'STAY_ENDED',
  PAYOUT_ACCOUNT_CHANGED = 'PAYOUT_ACCOUNT_CHANGED',
  USER_SIGNUP = 'USER_SIGNUP',

  // Phase 4: Rental Applications & Viewings
  RENTAL_APPLICATION_SUBMITTED = 'RENTAL_APPLICATION_SUBMITTED',
  RENTAL_APPLICATION_APPROVED = 'RENTAL_APPLICATION_APPROVED',
  RENTAL_APPLICATION_REJECTED = 'RENTAL_APPLICATION_REJECTED',
  RENTAL_APPLICATION_WITHDRAWN = 'RENTAL_APPLICATION_WITHDRAWN',
  VIEWING_REQUESTED = 'VIEWING_REQUESTED',
  VIEWING_CONFIRMED = 'VIEWING_CONFIRMED',
  VIEWING_COMPLETED = 'VIEWING_COMPLETED',

  // Phase 5: Tenancy & Leases
  RESERVATION_CONFIRMED = 'RESERVATION_CONFIRMED',
  LEASE_DRAFT_CREATED = 'LEASE_DRAFT_CREATED',
  LEASE_ISSUED = 'LEASE_ISSUED',
  LEASE_SIGNED = 'LEASE_SIGNED',
  LEASE_ACTIVATED = 'LEASE_ACTIVATED',
  LEASE_TERMINATED = 'LEASE_TERMINATED',
  LEASE_EXPIRED = 'LEASE_EXPIRED',

  // Phase 5: Security Deposits
  DEPOSIT_REQUESTED = 'DEPOSIT_REQUESTED',
  DEPOSIT_COLLECTED = 'DEPOSIT_COLLECTED',
  DEPOSIT_REFUNDED = 'DEPOSIT_REFUNDED',

  // Phase 5: Move-In
  MOVE_IN_SCHEDULED = 'MOVE_IN_SCHEDULED',
  MOVE_IN_COMPLETED = 'MOVE_IN_COMPLETED',
}

export interface DomainEvent<T = unknown> {
  id: string;
  type: DomainEventType;
  timestamp: string;
  metadata: {
    actorId?: string;
    traceId?: string;
  };
  payload: T;
}
