export enum DomainEventType {
  HOST_ONBOARDING_STARTED = 'HOST_ONBOARDING_STARTED',
  HOST_ONBOARDING_COMPLETED = 'HOST_ONBOARDING_COMPLETED',
  LISTING_CREATED = 'LISTING_CREATED',
  LISTING_PUBLISHED = 'LISTING_PUBLISHED',
  LISTING_DELETED = 'LISTING_DELETED',
  BOOKING_REQUESTED = 'BOOKING_REQUESTED',
  BOOKING_APPROVED = 'BOOKING_APPROVED',
  BOOKING_REJECTED = 'BOOKING_REJECTED',
  STAY_STARTED = 'STAY_STARTED',
  STAY_ENDED = 'STAY_ENDED',
  PAYOUT_ACCOUNT_CHANGED = 'PAYOUT_ACCOUNT_CHANGED',
  USER_SIGNUP = 'USER_SIGNUP',
}

export interface DomainEvent<T = unknown> {
  id: string;
  type: DomainEventType;
  timestamp: string;
  metadata: {
    actorId?: string;
    traceId?: string;
  };
  payload: T;
}
