export const POPULAR_LOCATIONS = [
  { city: 'Bangalore', image: '/images/placeholders/location-1.png' },
  { city: 'Mumbai', image: '/images/placeholders/location-1.png' },
  { city: 'New Delhi', image: '/images/placeholders/location-1.png' },
  { city: 'Hyderabad', image: '/images/placeholders/location-1.png' },
  { city: 'Pune', image: '/images/placeholders/location-1.png' },
  { city: 'Chennai', image: '/images/placeholders/location-1.png' },
  { city: 'Kolkata', image: '/images/placeholders/location-1.png' },
  { city: 'Ahmedabad', image: '/images/placeholders/location-1.png' },
  { city: 'Noida', image: '/images/placeholders/location-1.png' },
  { city: 'Gurgaon', image: '/images/placeholders/location-1.png' },
  { city: 'Jaipur', image: '/images/placeholders/location-1.png' },
  { city: 'Lucknow', image: '/images/placeholders/location-1.png' },
  { city: 'Chandigarh', image: '/images/placeholders/location-1.png' },
  { city: 'Kochi', image: '/images/placeholders/location-1.png' },
  { city: 'Indore', image: '/images/placeholders/location-1.png' },
];
