export enum NotificationEventType {
  // Profile
  PROFILE_PHONE_UPDATED = 'PROFILE_PHONE_UPDATED',
  PROFILE_AVATAR_UPDATED = 'PROFILE_AVATAR_UPDATED',
  PROFILE_ADDRESS_UPDATED = 'PROFILE_ADDRESS_UPDATED',
  PROFILE_COMPLETED = 'PROFILE_COMPLETED',

  // Messaging
  MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',

  // Bookings
  BOOKING_REQUESTED = 'BOOKING_REQUESTED',
  BOOKING_APPROVED = 'BOOKING_APPROVED',
  BOOKING_DECLINED = 'BOOKING_DECLINED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',

  // Stays
  STAY_STARTED = 'STAY_STARTED',
  STAY_ENDED = 'STAY_ENDED',

  // Security / System
  ACCOUNT_CREATED = 'ACCOUNT_CREATED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
}
