/*
==================================================
Domain: Accommodations Reference
Purpose: Master entities describing property types and available amenities.
Contains: 
- accommodation_types
- amenities
- accommodation_type_amenities
- triggers & RLS policies
==================================================
*/

CREATE TABLE public.accommodation_types (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT UNIQUE NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    description TEXT,
    icon TEXT,
    display_order INTEGER DEFAULT 0 NOT NULL,
    is_active BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE public.property_types (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    description TEXT,
    icon TEXT,
    display_order INTEGER DEFAULT 0 NOT NULL,
    is_active BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE public.amenity_categories (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    description TEXT,
    icon TEXT,
    display_order INTEGER DEFAULT 0 NOT NULL,
    is_active BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE public.amenities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    category_id SMALLINT REFERENCES public.amenity_categories(id),
    name TEXT UNIQUE NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    description TEXT,
    icon TEXT,
    is_filterable BOOLEAN DEFAULT true NOT NULL,
    is_featured BOOLEAN DEFAULT false NOT NULL,
    search_weight INTEGER DEFAULT 50 NOT NULL,
    display_order INTEGER DEFAULT 0 NOT NULL,
    is_active BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_amenities_category_id ON public.amenities(category_id);
CREATE INDEX IF NOT EXISTS idx_amenities_is_filterable ON public.amenities(is_filterable);
CREATE INDEX IF NOT EXISTS idx_amenities_is_featured ON public.amenities(is_featured);
CREATE INDEX IF NOT EXISTS idx_amenities_search_weight ON public.amenities(search_weight DESC);

CREATE TABLE public.accommodation_type_amenities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    accommodation_type_id UUID REFERENCES public.accommodation_types(id) ON DELETE CASCADE NOT NULL,
    amenity_id UUID REFERENCES public.amenities(id) ON DELETE CASCADE NOT NULL,
    is_default BOOLEAN DEFAULT false NOT NULL,
    is_required BOOLEAN DEFAULT false NOT NULL,
    display_order INTEGER DEFAULT 0 NOT NULL,
    category VARCHAR(50) DEFAULT 'Basic' NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    CONSTRAINT uk_accomm_type_amenity UNIQUE(accommodation_type_id, amenity_id)
);

CREATE INDEX IF NOT EXISTS idx_accomm_type_amenities_type_id ON public.accommodation_type_amenities(accommodation_type_id);
CREATE INDEX IF NOT EXISTS idx_accomm_type_amenities_amenity_id ON public.accommodation_type_amenities(amenity_id);

ALTER TABLE public.accommodation_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.amenities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.accommodation_type_amenities ENABLE ROW LEVEL SECURITY;

CREATE TRIGGER accommodation_types_updated_at 
  BEFORE UPDATE ON public.accommodation_types 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

CREATE TRIGGER amenities_updated_at 
  BEFORE UPDATE ON public.amenities 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

CREATE TRIGGER accommodation_type_amenities_updated_at 
  BEFORE UPDATE ON public.accommodation_type_amenities 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- RLS Policies
CREATE POLICY "Public can view accommodation types" ON public.accommodation_types
  FOR SELECT USING (true);

CREATE POLICY "Admins can manage accommodation types" ON public.accommodation_types
  FOR ALL USING (public.is_admin());

CREATE POLICY "Public can view amenities" ON public.amenities
  FOR SELECT USING (true);

CREATE POLICY "Admins can manage amenities" ON public.amenities
  FOR ALL USING (public.is_admin());

CREATE POLICY "Public can view accommodation type amenities" ON public.accommodation_type_amenities
  FOR SELECT USING (true);

CREATE POLICY "Admins can manage accommodation type amenities" ON public.accommodation_type_amenities
  FOR ALL USING (public.is_admin());

ALTER TABLE public.property_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.amenity_categories ENABLE ROW LEVEL SECURITY;

CREATE TRIGGER property_types_updated_at 
  BEFORE UPDATE ON public.property_types 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

CREATE TRIGGER amenity_categories_updated_at 
  BEFORE UPDATE ON public.amenity_categories 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

CREATE POLICY "Allow public read access on property_types" ON public.property_types
  FOR SELECT USING (is_active = true OR public.is_admin());

CREATE POLICY "Allow admin management on property_types" ON public.property_types
  FOR ALL USING (public.is_admin());

CREATE POLICY "Allow public read access on amenity_categories" ON public.amenity_categories
  FOR SELECT USING (is_active = true OR public.is_admin());

CREATE POLICY "Allow admin management on amenity_categories" ON public.amenity_categories
  FOR ALL USING (public.is_admin());