import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const schemaDir = __dirname;
const outputDir = path.join(__dirname, '..', 'migrations');
const outputFile = path.join(outputDir, '00000000000000_initial_schema.sql');

// Ensure the schema is built in exact sequential dependency order
const orderedFiles = [
  '00_extensions.sql',
  '01_types.sql',
  '02_shared_functions.sql',
  '03_identity.sql',
  '04_geography.sql',
  '05_accommodations.sql',
  '06_listings.sql',
  '07_listing_images.sql',
  '08_listing_pricing.sql',
  '09_listing_availability.sql',
  '10_bookings.sql',
  '11_stays.sql',
  '12_reviews.sql',
  '19_host_profiles.sql',
  '20_host_settings.sql',
  '13_notifications.sql',
  '14_messaging.sql',
  '15_calendar_sync.sql',
  '16_storage_buckets.sql',
  '17_search_functions.sql',
  '18_seed_reference_data.sql',
];

let unifiedSql = `-- THIS FILE IS AUTOGENERATED FROM supabase/schema/ DO NOT EDIT DIRECTLY\n\n`;

for (const file of orderedFiles) {
  const filePath = path.join(schemaDir, file);
  if (fs.existsSync(filePath)) {
    const content = fs.readFileSync(filePath, 'utf8');
    unifiedSql += `-- SOURCE: ${file}\n`;
    unifiedSql += content;
    unifiedSql += `\n\n`;
  } else {
    console.warn(`Warning: Could not find ${file}`);
  }
}

if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

fs.writeFileSync(outputFile, unifiedSql, 'utf8');
console.log(`Successfully built initial migration at ${outputFile}`);
