import fs from 'fs';
import path from 'path';

const schemaDir = path.join(process.cwd(), 'supabase', 'schema');
const outputDir = path.join(process.cwd(), 'supabase', 'migrations');
const outputFile = path.join(outputDir, '00000000000000_initial_schema.sql');

// Ensure the schema is built in exact dependency order
const orderedFiles = [
  '00_extensions.sql',
  '01_types.sql',
  '15_shared.sql',
  '02_identity.sql',
  '25_user_preferences.sql',
  '04_accommodations.sql',
  '05_listings.sql',
  '06_listing_images.sql',
  '07_pricing.sql',
  '09_bookings.sql',
  '10_stays.sql',
  '11_reviews.sql',
  '12_notifications.sql',
  '13_messaging.sql',
  '14_storage.sql',
  '08_availability.sql',
  '08_search.sql',
  '18_indexes.sql',
  '16_seed_reference_data.sql',
  '21_calendar_sync.sql',
  '22_cron_jobs.sql',
];

let unifiedSql = `-- THIS FILE IS AUTOGENERATED FROM supabase/schema/ DO NOT EDIT DIRECTLY\n\n`;

for (const file of orderedFiles) {
  const filePath = path.join(schemaDir, file);
  if (fs.existsSync(filePath)) {
    const content = fs.readFileSync(filePath, 'utf8');
    unifiedSql += `-- SOURCE: ${file}\n`;
    unifiedSql += content;
    unifiedSql += `\n\n`;
  } else {
    console.warn(`Warning: Could not find ${file}`);
  }
}

if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

fs.writeFileSync(outputFile, unifiedSql, 'utf8');
console.log(`Successfully built initial migration at ${outputFile}`);
