-- THIS FILE IS AUTOGENERATED FROM supabase/schema/ DO NOT EDIT DIRECTLY

-- SOURCE: 00_extensions.sql
/*
==================================================
Domain: Extensions
Purpose: Enables PostgreSQL extensions required by EliteStay.
Contains: 
- uuid-ossp
- pgcrypto
- pg_trgm
- btree_gist
- pg_cron
- pg_net
==================================================
*/

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE EXTENSION IF NOT EXISTS "btree_gist";
CREATE EXTENSION IF NOT EXISTS "pg_cron";
CREATE EXTENSION IF NOT EXISTS "pg_net";


-- SOURCE: 01_types.sql
/*
==================================================
Domain: Types
Purpose: Defines shared types and enums used across all domains.
Contains: 
- user_role
- user_occupation
- listing_status
- booking_status
- stay_status
- billing_period
- availability_status
- availability_source
- occupancy_type
- gender
- gender_preference
- furnishing
- sync_direction
==================================================
*/

CREATE TYPE public.user_role AS ENUM ('guest', 'host', 'admin');
CREATE TYPE public.user_occupation AS ENUM ('student', 'software_engineer', 'healthcare_professional', 'education', 'design_creative', 'finance_accounting', 'marketing_sales', 'entrepreneur_founder', 'freelancer', 'other');
CREATE TYPE public.listing_status AS ENUM ('draft', 'ready', 'pending_review', 'published', 'paused', 'archived');
CREATE TYPE public.booking_status AS ENUM ('pending', 'approved', 'rejected', 'cancelled', 'expired');
CREATE TYPE public.stay_status AS ENUM ('upcoming', 'active', 'extended', 'checked_out', 'completed', 'terminated');
CREATE TYPE public.billing_period AS ENUM ('day', 'week', 'month', 'semester', 'year');
CREATE TYPE public.availability_status AS ENUM ('available', 'occupied', 'unavailable');
CREATE TYPE public.availability_source AS ENUM ('booking', 'manual_block', 'external_calendar', 'maintenance');
CREATE TYPE public.occupancy_type AS ENUM ('private', 'shared', 'mixed');
CREATE TYPE public.gender AS ENUM ('male', 'female');
CREATE TYPE public.gender_preference AS ENUM ('any', 'male', 'female');
CREATE TYPE public.furnishing AS ENUM ('unfurnished', 'semi_furnished', 'fully_furnished');
CREATE TYPE public.sync_direction AS ENUM ('import', 'export', 'both');


-- SOURCE: 02_shared_functions.sql
/*
==================================================
Domain: Shared Functions
Purpose: Cross-cutting utilities and shared functions.
Contains: 
- updated_at trigger helper
- public_id generator
- public_id immutability triggers
==================================================
*/

CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

/*
  uuid_to_public_id()
  Contract:
  - Deterministic
  - One-to-one mapping
  - Immutable output
  - Entire 128-bit UUID encoded
  - No randomness
  - URL safe (Crockford Base32)
  - Case insensitive
  - Never change algorithm (Treat as permanent contract)
*/
CREATE OR REPLACE FUNCTION public.uuid_to_public_id(input_uuid UUID)
RETURNS TEXT
LANGUAGE plpgsql
IMMUTABLE STRICT
SET search_path = ''
AS $$
DECLARE
    bytes BYTEA := uuid_send(input_uuid);
    res TEXT := '';
    chars TEXT := '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
    n NUMERIC := 0;
    i INTEGER;
BEGIN
    IF input_uuid IS NULL THEN
        RETURN NULL;
    END IF;

    FOR i IN 0..15 LOOP
        n := n * 256 + get_byte(bytes, i);
    END LOOP;
    
    IF n = 0 THEN
        RETURN lpad('0', 26, '0');
    END IF;
    
    WHILE n > 0 LOOP
        res := substr(chars, (n % 32)::integer + 1, 1) || res;
        n := floor(n / 32);
    END LOOP;
    
    RETURN lpad(res, 26, '0');
END;
$$;

CREATE OR REPLACE FUNCTION public.trigger_set_public_id()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
    IF NEW.id IS NULL THEN
        NEW.id := gen_random_uuid();
    END IF;
    
    IF NEW.public_id IS NULL THEN
        NEW.public_id := public.uuid_to_public_id(NEW.id);
    END IF;
    
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.trigger_prevent_public_id_update()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
    IF OLD.public_id IS NOT NULL AND NEW.public_id IS DISTINCT FROM OLD.public_id THEN
        RAISE EXCEPTION 'public_id is immutable and cannot be updated';
    END IF;
    RETURN NEW;
END;
$$;


-- SOURCE: 03_identity.sql
/*
==================================================
Domain: Identity & Preferences
Purpose: Everything related to users, roles, preferences, and authentication workflows.
Contains: 
- profiles
- user_preferences
- identity functions & triggers
- RLS policies
- account deletion workflow
==================================================
*/

-- 1. Profiles Table
CREATE TABLE public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    display_name TEXT,
    full_name TEXT,
    avatar_storage_path TEXT,
    phone TEXT,
    role public.user_role DEFAULT 'guest'::public.user_role NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    bio TEXT,
    date_of_birth DATE,
    gender public.gender,
    occupation public.user_occupation,
    username TEXT CHECK (username IS NULL OR (char_length(username) >= 3 AND char_length(username) <= 30 AND username ~ '^[a-z0-9_]+$'::text)),
    timezone TEXT
);

CREATE INDEX IF NOT EXISTS profiles_role_idx ON public.profiles(role);
CREATE INDEX IF NOT EXISTS profiles_username_idx ON public.profiles(username);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 2. User Preferences Table
CREATE TABLE public.user_preferences (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    privacy JSONB NOT NULL DEFAULT '{
      "allow_host_messages": true,
      "show_profile_photo": true,
      "show_reviews": true,
      "allow_search_indexing": false
    }'::jsonb,
    notifications JSONB NOT NULL DEFAULT '{
      "email": true,
      "push": false,
      "sms": false,
      "marketing": false
    }'::jsonb,
    security JSONB NOT NULL DEFAULT '{
      "two_factor_auth": false,
      "allow_new_device_login": true,
      "remember_device": true
    }'::jsonb,
    hosting JSONB NOT NULL DEFAULT '{
      "accept_booking_requests": true,
      "instant_booking": false,
      "auto_approve_reservations": false
    }'::jsonb,
    communication JSONB NOT NULL DEFAULT '{
      "promotional_messages": false,
      "support_contact": true,
      "share_contact_after_booking": true
    }'::jsonb,
    data JSONB NOT NULL DEFAULT '{
      "share_analytics": false,
      "personalized_recommendations": true,
      "cookie_preferences": "essential"
    }'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.user_preferences ENABLE ROW LEVEL SECURITY;

-- 3. Helper Functions (Defined early for use in RLS and triggers)
CREATE OR REPLACE FUNCTION public.is_host()
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  RETURN (
    SELECT role = 'host'::public.user_role 
    FROM public.profiles 
    WHERE id = auth.uid()
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  RETURN (
    SELECT role = 'admin'::public.user_role 
    FROM public.profiles 
    WHERE id = auth.uid()
  );
END;
$$;

-- 4. RLS Policies for Profiles
CREATE POLICY "Users can read own profile" ON public.profiles
  FOR SELECT USING (auth.uid() = id OR public.is_admin());

CREATE POLICY "Users can update own profile" ON public.profiles
  FOR UPDATE USING (auth.uid() = id OR public.is_admin());

-- 5. RLS Policies for User Preferences
CREATE POLICY "Users can read own preferences" ON public.user_preferences
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can update own preferences" ON public.user_preferences
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own preferences" ON public.user_preferences
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 6. Profile Immutability Protection
CREATE OR REPLACE FUNCTION public.protect_identity_fields()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF NOT public.is_admin() THEN
    NEW.id = OLD.id;
    NEW.role = OLD.role;
    NEW.created_at = OLD.created_at;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER enforce_profile_immutability
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE PROCEDURE public.protect_identity_fields();

-- 7. Handle New User Signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.profiles (
    id, 
    full_name, 
    avatar_storage_path, 
    role,
    created_at,
    updated_at
  ) VALUES (
    NEW.id, 
    NEW.raw_user_meta_data->>'full_name', 
    NEW.raw_user_meta_data->>'avatar_url', 
    'guest'::public.user_role,
    NOW(),
    NOW()
  );

  INSERT INTO public.user_preferences (user_id)
  VALUES (NEW.id);

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 8. Updated_at Triggers
CREATE TRIGGER profiles_updated_at 
  BEFORE UPDATE ON public.profiles 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

CREATE TRIGGER user_preferences_updated_at 
  BEFORE UPDATE ON public.user_preferences 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- 9. Account Deletion RPC and Triggers
CREATE OR REPLACE FUNCTION public.delete_user_account()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    v_user_id uuid;
BEGIN
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Not authenticated';
    END IF;
    
    DELETE FROM auth.users WHERE id = v_user_id;
    RETURN jsonb_build_object('success', true);
END;
$$;

CREATE OR REPLACE FUNCTION public.handle_user_delete_cleanup()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
    UPDATE public.stays
    SET created_by = NULL
    WHERE created_by = OLD.id;
    RETURN OLD;
END;
$$;

DROP TRIGGER IF EXISTS tr_on_user_delete_cleanup ON auth.users;
CREATE TRIGGER tr_on_user_delete_cleanup
    BEFORE DELETE ON auth.users
    FOR EACH ROW
    EXECUTE PROCEDURE public.handle_user_delete_cleanup();


-- SOURCE: 04_geography.sql
/*
==================================================
Domain: Geography & Locations
Purpose: Master reference data hierarchy for locations and geocoding cache.
Contains: 
- countries
- states
- cities
- geocoding_cache
- geography triggers & RLS policies
==================================================
*/

-- 1. Create Countries Table
CREATE TABLE public.countries (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    external_code TEXT UNIQUE NOT NULL,
    name TEXT UNIQUE NOT NULL,
    iso2 TEXT UNIQUE NOT NULL,
    iso3 TEXT UNIQUE NOT NULL,
    currency_code TEXT,
    phone_code TEXT,
    timezone_default TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 2. Create States Table
CREATE TABLE public.states (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    country_id BIGINT REFERENCES public.countries(id) ON DELETE CASCADE NOT NULL,
    external_code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    code TEXT NOT NULL,
    slug TEXT NOT NULL,
    population BIGINT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    UNIQUE(country_id, slug)
);

-- 3. Create Cities Table
CREATE TABLE public.cities (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    state_id BIGINT REFERENCES public.states(id) ON DELETE CASCADE NOT NULL,
    external_code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    search_aliases TEXT[] DEFAULT '{}',
    slug TEXT NOT NULL,
    latitude DOUBLE PRECISION CHECK (latitude >= -90 AND latitude <= 90),
    longitude DOUBLE PRECISION CHECK (longitude >= -180 AND longitude <= 180),
    timezone TEXT,
    cover_image_storage_path TEXT,
    description TEXT,
    population BIGINT,
    is_capital BOOLEAN DEFAULT false NOT NULL,
    is_metro BOOLEAN DEFAULT false NOT NULL,
    is_featured BOOLEAN DEFAULT false NOT NULL,
    is_active BOOLEAN DEFAULT true NOT NULL,
    sort_order INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    UNIQUE(state_id, slug)
);

-- 4. Create Geocoding Cache Table
CREATE TABLE public.geocoding_cache (
    cache_key TEXT PRIMARY KEY,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    formatted_address TEXT NOT NULL,
    provider TEXT NOT NULL,
    provider_place_id TEXT,
    confidence NUMERIC,
    geocoded_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ DEFAULT NOW() + INTERVAL '5 years'
);

-- 5. Triggers for updated_at
CREATE TRIGGER countries_updated_at 
  BEFORE UPDATE ON public.countries FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

CREATE TRIGGER states_updated_at 
  BEFORE UPDATE ON public.states FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

CREATE TRIGGER cities_updated_at 
  BEFORE UPDATE ON public.cities FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- 6. Indexes
CREATE INDEX IF NOT EXISTS cities_state_idx ON public.cities(state_id);
CREATE INDEX IF NOT EXISTS cities_active_idx ON public.cities(is_active);
CREATE INDEX IF NOT EXISTS cities_featured_idx ON public.cities(is_featured);

-- 7. RLS Policies
ALTER TABLE public.countries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.states ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.geocoding_cache ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view active countries" ON public.countries FOR SELECT USING (true);
CREATE POLICY "Public can view active states" ON public.states FOR SELECT USING (true);
CREATE POLICY "Public can view active cities" ON public.cities FOR SELECT USING (is_active = true OR public.is_admin());

CREATE POLICY "Only admins can manage countries" ON public.countries FOR ALL USING (public.is_admin());
CREATE POLICY "Only admins can manage states" ON public.states FOR ALL USING (public.is_admin());
CREATE POLICY "Only admins can manage cities" ON public.cities FOR ALL USING (public.is_admin());

-- Geocoding Cache Policies
CREATE POLICY "Enable read access for authenticated users" ON public.geocoding_cache FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable insert access for authenticated users" ON public.geocoding_cache FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update access for authenticated users" ON public.geocoding_cache FOR UPDATE TO authenticated USING (true) WITH CHECK (true);


-- SOURCE: 05_accommodations.sql
/*
==================================================
Domain: Accommodations Reference
Purpose: Master entities describing property types and available amenities.
Contains: 
- accommodation_types
- amenities
- triggers & RLS policies
==================================================
*/

CREATE TABLE public.accommodation_types (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT UNIQUE NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE public.amenities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT UNIQUE NOT NULL,
    icon TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

ALTER TABLE public.accommodation_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.amenities ENABLE ROW LEVEL SECURITY;

CREATE TRIGGER accommodation_types_updated_at 
  BEFORE UPDATE ON public.accommodation_types 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

CREATE TRIGGER amenities_updated_at 
  BEFORE UPDATE ON public.amenities 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- RLS Policies
CREATE POLICY "Public can view accommodation types" ON public.accommodation_types
  FOR SELECT USING (true);

CREATE POLICY "Admins can manage accommodation types" ON public.accommodation_types
  FOR ALL USING (public.is_admin());

CREATE POLICY "Public can view amenities" ON public.amenities
  FOR SELECT USING (true);

CREATE POLICY "Admins can manage amenities" ON public.amenities
  FOR ALL USING (public.is_admin());


-- SOURCE: 06_listings.sql
/*
==================================================
Domain: Listings
Purpose: Core marketplace domain for property listings and host workflows.
Contains: 
- listings
- listing_amenities
- listing_build_progress
- is_listing_owner helper function
- triggers, RLS, & performance indexes
==================================================
*/

CREATE TABLE public.listings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    public_id TEXT UNIQUE NOT NULL,
    host_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    accommodation_type_id UUID REFERENCES public.accommodation_types(id) ON DELETE RESTRICT NOT NULL,
    property_type TEXT DEFAULT 'Apartment' NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    max_occupants INTEGER DEFAULT 1 NOT NULL,
    occupancy_type public.occupancy_type DEFAULT 'private'::public.occupancy_type NOT NULL,
    gender_preference public.gender_preference DEFAULT 'any'::public.gender_preference NOT NULL,
    furnishing public.furnishing DEFAULT 'unfurnished'::public.furnishing NOT NULL,
    
    -- Location Fields
    state TEXT,
    city TEXT,
    city_id BIGINT REFERENCES public.cities(id) ON DELETE SET NULL,
    locality TEXT,
    postal_code TEXT,
    latitude DOUBLE PRECISION CHECK (latitude >= -90 AND latitude <= 90),
    longitude DOUBLE PRECISION CHECK (longitude >= -180 AND longitude <= 180),
    formatted_address TEXT,
    
    status public.listing_status DEFAULT 'draft'::public.listing_status NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    
    CONSTRAINT published_listing_requires_coordinates CHECK (
        status <> 'published'
        OR (latitude IS NOT NULL AND longitude IS NOT NULL AND formatted_address IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_listings_public_id ON public.listings(public_id);
CREATE INDEX IF NOT EXISTS idx_listings_host_id ON public.listings(host_id);
CREATE INDEX IF NOT EXISTS idx_listings_lat_lng ON public.listings(latitude, longitude);
CREATE INDEX IF NOT EXISTS listings_city_idx ON public.listings(city_id);

CREATE OR REPLACE FUNCTION public.is_listing_owner(p_listing_id uuid)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 
    FROM public.listings 
    WHERE id = p_listing_id AND host_id = auth.uid()
  );
END;
$$;

CREATE TABLE public.listing_amenities (
    listing_id UUID REFERENCES public.listings(id) ON DELETE CASCADE NOT NULL,
    amenity_id UUID REFERENCES public.amenities(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    PRIMARY KEY (listing_id, amenity_id)
);

CREATE INDEX IF NOT EXISTS listing_amenities_amenity_idx ON public.listing_amenities(amenity_id);

CREATE TABLE public.listing_build_progress (
    listing_id UUID PRIMARY KEY REFERENCES public.listings(id) ON DELETE CASCADE,
    step_completed TEXT,
    last_step TEXT NOT NULL DEFAULT 'accommodation',
    percent_complete INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Triggers
CREATE TRIGGER listings_updated_at 
  BEFORE UPDATE ON public.listings 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

CREATE TRIGGER listings_set_public_id
  BEFORE INSERT ON public.listings
  FOR EACH ROW EXECUTE PROCEDURE public.trigger_set_public_id();

CREATE TRIGGER listings_prevent_public_id_update
  BEFORE UPDATE ON public.listings
  FOR EACH ROW EXECUTE PROCEDURE public.trigger_prevent_public_id_update();

CREATE TRIGGER listing_amenities_updated_at 
  BEFORE UPDATE ON public.listing_amenities 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

CREATE TRIGGER listing_build_progress_updated_at 
  BEFORE UPDATE ON public.listing_build_progress 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- RLS
ALTER TABLE public.listings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.listing_amenities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.listing_build_progress ENABLE ROW LEVEL SECURITY;

-- Listings Policies
CREATE POLICY "Public can read published listings" ON public.listings
  FOR SELECT USING (status = 'published'::public.listing_status OR host_id = auth.uid() OR public.is_admin());

CREATE POLICY "Hosts can insert listings" ON public.listings
  FOR INSERT WITH CHECK (
    auth.uid() IS NOT NULL AND 
    (public.is_host() OR public.is_admin()) AND
    host_id = auth.uid()
  );

CREATE POLICY "Hosts can update own listings" ON public.listings
  FOR UPDATE USING (host_id = auth.uid() OR public.is_admin());

CREATE POLICY "Hosts can delete own listings" ON public.listings
  FOR DELETE USING (host_id = auth.uid() OR public.is_admin());

-- Listing Amenities Policies
CREATE POLICY "Public can view listing amenities" ON public.listing_amenities
  FOR SELECT USING (true);

CREATE POLICY "Hosts can manage own listing amenities" ON public.listing_amenities
  FOR ALL USING (
    EXISTS (
        SELECT 1 FROM public.listings l 
        WHERE l.id = listing_amenities.listing_id 
        AND (l.host_id = auth.uid() OR public.is_admin())
    )
  );

-- Listing Build Progress Policies
CREATE POLICY "Hosts can view own listing progress" ON public.listing_build_progress
  FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM public.listings l 
        WHERE l.id = listing_build_progress.listing_id 
        AND (l.host_id = auth.uid() OR public.is_admin())
    )
  );

CREATE POLICY "Hosts can insert own listing progress" ON public.listing_build_progress
  FOR INSERT WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.listings l 
        WHERE l.id = listing_build_progress.listing_id 
        AND (l.host_id = auth.uid() OR public.is_admin())
    )
  );

CREATE POLICY "Hosts can update own listing progress" ON public.listing_build_progress
  FOR UPDATE USING (
    EXISTS (
        SELECT 1 FROM public.listings l 
        WHERE l.id = listing_build_progress.listing_id 
        AND (l.host_id = auth.uid() OR public.is_admin())
    )
  );

CREATE POLICY "Hosts can delete own listing progress" ON public.listing_build_progress
  FOR DELETE USING (
    EXISTS (
        SELECT 1 FROM public.listings l 
        WHERE l.id = listing_build_progress.listing_id 
        AND (l.host_id = auth.uid() OR public.is_admin())
    )
  );


-- SOURCE: 07_listing_images.sql
/*
==================================================
Domain: Listing Images
Purpose: Dedicated domain for property images and gallery metadata.
Contains: 
- listing_images
- triggers & RLS policies
==================================================
*/

CREATE TABLE public.listing_images (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    listing_id UUID REFERENCES public.listings(id) ON DELETE CASCADE NOT NULL,
    storage_path TEXT NOT NULL,
    display_order INTEGER DEFAULT 0 NOT NULL,
    is_cover BOOLEAN DEFAULT false,
    file_size INTEGER,
    mime_type TEXT,
    width INTEGER,
    height INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Ensure only one cover image per listing
CREATE UNIQUE INDEX IF NOT EXISTS idx_listing_images_cover 
  ON public.listing_images (listing_id) 
  WHERE is_cover = true;

CREATE INDEX IF NOT EXISTS idx_listing_images_listing_id ON public.listing_images(listing_id);

CREATE TRIGGER listing_images_updated_at 
  BEFORE UPDATE ON public.listing_images 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

ALTER TABLE public.listing_images ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view listing images" ON public.listing_images
  FOR SELECT USING (true);

CREATE POLICY "Hosts can manage own listing images" ON public.listing_images
  FOR ALL USING (
    EXISTS (
        SELECT 1 FROM public.listings l 
        WHERE l.id = listing_images.listing_id 
        AND (l.host_id = auth.uid() OR public.is_admin())
    )
  );


-- SOURCE: 08_listing_pricing.sql
/*
==================================================
Domain: Listing Pricing
Purpose: Financial terms, pricing models, and duration constraints for listings.
Contains: 
- listing_prices
- triggers & RLS policies
==================================================
*/

CREATE TABLE public.listing_prices (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    listing_id UUID REFERENCES public.listings(id) ON DELETE CASCADE NOT NULL UNIQUE,
    amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
    currency TEXT DEFAULT 'INR' NOT NULL CHECK (currency = 'INR'),
    billing_period public.billing_period NOT NULL,
    security_deposit NUMERIC(12, 2) DEFAULT 0 NOT NULL,
    maintenance_fee NUMERIC(12, 2) DEFAULT 0 NOT NULL,
    maintenance_fee_period public.billing_period DEFAULT 'semester'::public.billing_period,
    minimum_duration INTEGER DEFAULT 1 NOT NULL,
    maximum_duration INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TRIGGER listing_prices_updated_at 
  BEFORE UPDATE ON public.listing_prices 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

ALTER TABLE public.listing_prices ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view listing prices" ON public.listing_prices
  FOR SELECT USING (true);

CREATE POLICY "Hosts can manage own listing prices" ON public.listing_prices
  FOR ALL USING (
    EXISTS (
        SELECT 1 FROM public.listings l 
        WHERE l.id = listing_prices.listing_id 
        AND (l.host_id = auth.uid() OR public.is_admin())
    )
  );


-- SOURCE: 09_listing_availability.sql
/*
==================================================
Domain: Listing Availability
Purpose: Tracks property availability periods, occupancies, and host blocks.
Contains: 
- listing_availability
- triggers, RLS, & range indexes
==================================================
*/

CREATE TABLE public.listing_availability (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    listing_id UUID REFERENCES public.listings(id) ON DELETE CASCADE NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    available_units INTEGER DEFAULT 1 NOT NULL,
    status public.availability_status DEFAULT 'available'::public.availability_status NOT NULL,
    source public.availability_source DEFAULT 'manual_block'::public.availability_source NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    CONSTRAINT check_availability_dates CHECK (end_date >= start_date)
);

-- Composite index for date range availability searches
CREATE INDEX IF NOT EXISTS idx_listing_availability_range ON public.listing_availability (listing_id, start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_listing_availability_status ON public.listing_availability (status);

CREATE TRIGGER listing_availability_updated_at 
  BEFORE UPDATE ON public.listing_availability 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

ALTER TABLE public.listing_availability ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view availability" ON public.listing_availability
  FOR SELECT USING (true);

CREATE POLICY "Hosts can manage availability" ON public.listing_availability
  FOR ALL USING (
    EXISTS (
        SELECT 1 FROM public.listings l 
        WHERE l.id = listing_availability.listing_id 
        AND (l.host_id = auth.uid() OR public.is_admin())
    )
  );


-- SOURCE: 10_bookings.sql
/*
==================================================
Domain: Bookings
Purpose: Booking request lifecycle, financial term snapshots, and domain events.
Contains: 
- bookings
- booking_events
- transition_booking atomic RPC
- triggers, RLS, & composite indexes
==================================================
*/

CREATE TABLE public.bookings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    listing_id UUID REFERENCES public.listings(id) ON DELETE CASCADE NOT NULL,
    guest_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    requested_move_in DATE NOT NULL,
    requested_duration INTEGER NOT NULL CHECK (requested_duration > 0),
    message TEXT,
    snapshot_monthly_rent NUMERIC(12, 2) NOT NULL,
    snapshot_security_deposit NUMERIC(12, 2) NOT NULL,
    snapshot_maintenance_fee NUMERIC(12, 2) NOT NULL,
    snapshot_billing_period public.billing_period NOT NULL,
    snapshot_minimum_stay INTEGER NOT NULL,
    expires_at TIMESTAMPTZ,
    status public.booking_status DEFAULT 'pending'::public.booking_status NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_bookings_listing_id ON public.bookings(listing_id);
CREATE INDEX IF NOT EXISTS idx_bookings_guest_id ON public.bookings(guest_id);
CREATE INDEX IF NOT EXISTS idx_bookings_guest_status ON public.bookings(guest_id, status);
CREATE INDEX IF NOT EXISTS idx_bookings_listing_status ON public.bookings(listing_id, status);

CREATE TABLE public.booking_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id UUID NOT NULL REFERENCES public.bookings(id) ON DELETE CASCADE,
    actor_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    action TEXT NOT NULL,
    previous_status public.booking_status,
    new_status public.booking_status,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_booking_events_booking_id ON public.booking_events(booking_id);

CREATE TRIGGER bookings_updated_at 
  BEFORE UPDATE ON public.bookings 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.booking_events ENABLE ROW LEVEL SECURITY;

-- Bookings RLS Policies
CREATE POLICY "Guests can view own bookings" ON public.bookings
  FOR SELECT USING (guest_id = auth.uid() OR public.is_admin());

CREATE POLICY "Hosts can view bookings for their listings" ON public.bookings
  FOR SELECT USING (public.is_listing_owner(listing_id) OR public.is_admin());

CREATE POLICY "Authenticated users can create bookings" ON public.bookings
  FOR INSERT WITH CHECK (
    auth.uid() IS NOT NULL AND guest_id = auth.uid()
  );

CREATE POLICY "Guests can cancel pending bookings" ON public.bookings
  FOR UPDATE USING (guest_id = auth.uid() AND status = 'pending'::public.booking_status)
  WITH CHECK (guest_id = auth.uid() AND status = 'cancelled'::public.booking_status);

CREATE POLICY "Hosts can approve or reject pending bookings" ON public.bookings
  FOR UPDATE USING (public.is_listing_owner(listing_id) AND status = 'pending'::public.booking_status)
  WITH CHECK (public.is_listing_owner(listing_id) AND status IN ('approved'::public.booking_status, 'rejected'::public.booking_status));

CREATE POLICY "Admins can update all bookings" ON public.bookings
  FOR UPDATE USING (public.is_admin());

CREATE POLICY "Admins can delete bookings" ON public.bookings
  FOR DELETE USING (public.is_admin());

-- Booking Events RLS Policies
CREATE POLICY "Users can view events for their bookings" ON public.booking_events
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.bookings b
      WHERE b.id = booking_events.booking_id
      AND (b.guest_id = auth.uid() OR public.is_listing_owner(b.listing_id) OR public.is_admin())
    )
  );

CREATE POLICY "Users can insert events for their bookings" ON public.booking_events
  FOR INSERT WITH CHECK (
    actor_id = auth.uid() AND
    EXISTS (
      SELECT 1 FROM public.bookings b
      WHERE b.id = booking_events.booking_id
      AND (b.guest_id = auth.uid() OR public.is_listing_owner(b.listing_id) OR public.is_admin())
    )
  );

-- Atomic booking transition RPC
CREATE OR REPLACE FUNCTION public.transition_booking(
  p_booking_id uuid,
  p_current_status public.booking_status,
  p_new_status public.booking_status,
  p_actor_id uuid,
  p_metadata jsonb DEFAULT '{}'::jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_booking public.bookings%ROWTYPE;
BEGIN
  -- Lock the row to prevent race conditions
  SELECT * INTO v_booking
  FROM public.bookings
  WHERE id = p_booking_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Booking not found';
  END IF;

  IF v_booking.status != p_current_status THEN
    RAISE EXCEPTION 'Booking state changed by another process (expected %, got %)', p_current_status, v_booking.status;
  END IF;

  -- Update booking status
  UPDATE public.bookings
  SET status = p_new_status
  WHERE id = p_booking_id;

  -- Insert audit domain event
  INSERT INTO public.booking_events (
    booking_id,
    action,
    actor_id,
    previous_status,
    new_status,
    metadata
  ) VALUES (
    p_booking_id,
    p_new_status::text,
    p_actor_id,
    p_current_status,
    p_new_status,
    p_metadata
  );

  RETURN jsonb_build_object('success', true);
END;
$$;


-- SOURCE: 11_stays.sql
/*
==================================================
Domain: Stays
Purpose: Tenancy management, active residences, and check-in/check-out lifecycle.
Contains: 
- stays
- stay_events
- transition_stay atomic RPC
- triggers, RLS, & composite indexes
==================================================
*/

CREATE TABLE public.stays (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    listing_id UUID REFERENCES public.listings(id) ON DELETE CASCADE NOT NULL,
    guest_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    created_from_booking_id UUID REFERENCES public.bookings(id) ON DELETE SET NULL,
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    expected_move_in_date DATE NOT NULL,
    actual_move_in_date DATE,
    expected_move_out_date DATE NOT NULL,
    actual_move_out_date DATE,
    agreed_amount NUMERIC(12, 2) NOT NULL,
    agreed_billing_period public.billing_period NOT NULL,
    security_deposit_paid NUMERIC(12, 2) DEFAULT 0 NOT NULL,
    status public.stay_status DEFAULT 'upcoming'::public.stay_status NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    CONSTRAINT check_stay_dates CHECK (expected_move_out_date > expected_move_in_date)
);

CREATE INDEX IF NOT EXISTS idx_stays_created_from_booking_id ON public.stays(created_from_booking_id);
CREATE INDEX IF NOT EXISTS idx_stays_guest_status ON public.stays(guest_id, status);
CREATE INDEX IF NOT EXISTS idx_stays_listing_status ON public.stays(listing_id, status);

CREATE TABLE public.stay_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    stay_id UUID NOT NULL REFERENCES public.stays(id) ON DELETE CASCADE,
    actor_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    action TEXT NOT NULL,
    previous_status public.stay_status,
    new_status public.stay_status,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_stay_events_stay_id ON public.stay_events(stay_id);

CREATE TRIGGER stays_updated_at 
  BEFORE UPDATE ON public.stays 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

ALTER TABLE public.stays ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stay_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Guests can view own stays" ON public.stays
  FOR SELECT USING (guest_id = auth.uid() OR public.is_admin());

CREATE POLICY "Hosts can view stays for their listings" ON public.stays
  FOR SELECT USING (public.is_listing_owner(listing_id) OR public.is_admin());

CREATE POLICY "Hosts can manage stays" ON public.stays
  FOR ALL USING (public.is_listing_owner(listing_id) OR public.is_admin());

-- Stay Events RLS Policies
CREATE POLICY "Users can view events for their stays" ON public.stay_events
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.stays s
      WHERE s.id = stay_events.stay_id
      AND (s.guest_id = auth.uid() OR public.is_listing_owner(s.listing_id) OR public.is_admin())
    )
  );

CREATE POLICY "Users can insert events for their stays" ON public.stay_events
  FOR INSERT WITH CHECK (
    actor_id = auth.uid() AND
    EXISTS (
      SELECT 1 FROM public.stays s
      WHERE s.id = stay_events.stay_id
      AND (s.guest_id = auth.uid() OR public.is_listing_owner(s.listing_id) OR public.is_admin())
    )
  );

-- Atomic stay transition RPC
CREATE OR REPLACE FUNCTION public.transition_stay(
  p_stay_id uuid,
  p_current_status public.stay_status,
  p_new_status public.stay_status,
  p_actor_id uuid,
  p_updates jsonb DEFAULT '{}'::jsonb,
  p_metadata jsonb DEFAULT '{}'::jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_stay public.stays%ROWTYPE;
BEGIN
  -- Lock row against concurrent transitions
  SELECT * INTO v_stay
  FROM public.stays
  WHERE id = p_stay_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Stay not found';
  END IF;

  IF v_stay.status != p_current_status THEN
    RAISE EXCEPTION 'Stay state changed by another process (expected %, got %)', p_current_status, v_stay.status;
  END IF;

  -- Apply status transition and date updates
  UPDATE public.stays
  SET 
    status = p_new_status,
    actual_move_in_date = COALESCE((p_updates->>'actual_move_in_date')::date, actual_move_in_date),
    actual_move_out_date = COALESCE((p_updates->>'actual_move_out_date')::date, actual_move_out_date)
  WHERE id = p_stay_id;

  -- Insert domain event log
  INSERT INTO public.stay_events (
    stay_id,
    action,
    actor_id,
    previous_status,
    new_status,
    metadata
  ) VALUES (
    p_stay_id,
    p_new_status::text,
    p_actor_id,
    p_current_status,
    p_new_status,
    p_metadata
  );

  RETURN jsonb_build_object('success', true);
END;
$$;


-- SOURCE: 12_reviews.sql
/*
==================================================
Domain: Reviews
Purpose: Guest ratings, property evaluations, and review verifications.
Contains: 
- reviews
- triggers, RLS, & listing index
==================================================
*/

CREATE TABLE public.reviews (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    stay_id UUID REFERENCES public.stays(id) ON DELETE RESTRICT NOT NULL UNIQUE,
    listing_id UUID REFERENCES public.listings(id) ON DELETE CASCADE NOT NULL,
    guest_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT CHECK (comment IS NULL OR char_length(comment) >= 10),
    host_reply TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_reviews_listing_id ON public.reviews(listing_id);
CREATE INDEX IF NOT EXISTS idx_reviews_guest_id ON public.reviews(guest_id);

CREATE TRIGGER reviews_updated_at 
  BEFORE UPDATE ON public.reviews 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view reviews" ON public.reviews
  FOR SELECT USING (true);

CREATE POLICY "Guests can create reviews for their completed stays" ON public.reviews
  FOR INSERT WITH CHECK (
    auth.uid() IS NOT NULL AND 
    guest_id = auth.uid() AND
    EXISTS (
        SELECT 1 FROM public.stays s
        WHERE s.id = reviews.stay_id 
        AND s.guest_id = auth.uid()
        AND s.status IN ('checked_out'::public.stay_status, 'completed'::public.stay_status)
    )
  );

CREATE POLICY "Hosts can reply to reviews on their listings" ON public.reviews
  FOR UPDATE USING (public.is_listing_owner(listing_id) OR public.is_admin())
  WITH CHECK (public.is_listing_owner(listing_id) OR public.is_admin());

CREATE POLICY "Guests can update their own reviews" ON public.reviews
  FOR UPDATE USING (guest_id = auth.uid() OR public.is_admin())
  WITH CHECK (guest_id = auth.uid() OR public.is_admin());

CREATE POLICY "Admins can manage reviews" ON public.reviews
  FOR ALL USING (public.is_admin());


-- SOURCE: 13_notifications.sql
/*
==================================================
Domain: Notifications
Purpose: System alerts, booking notification triggers, and communication tracking.
Contains: 
- notifications
- RLS policies & performance indexes
==================================================
*/

CREATE TABLE public.notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    type TEXT NOT NULL,
    data JSONB DEFAULT '{}'::jsonb,
    read_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Partial index for fast queries of unread notifications
CREATE INDEX IF NOT EXISTS idx_notifications_unread ON public.notifications (user_id) WHERE read_at IS NULL;
-- Composite index for fetching all notifications sorted by timestamp
CREATE INDEX IF NOT EXISTS idx_notifications_user_created ON public.notifications (user_id, created_at DESC);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own notifications" ON public.notifications
  FOR SELECT USING (user_id = auth.uid() OR public.is_admin());

CREATE POLICY "Users can mark own notifications as read" ON public.notifications
  FOR UPDATE USING (user_id = auth.uid() OR public.is_admin());

CREATE POLICY "System can insert notifications" ON public.notifications
  FOR INSERT WITH CHECK (true);


-- SOURCE: 14_messaging.sql
/*
==================================================
Domain: Messaging
Purpose: Real-time user communications linked to bookings and stays.
Contains: 
- conversations
- messages
- triggers, RLS, & foreign key indexes
==================================================
*/

CREATE TABLE public.conversations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id UUID REFERENCES public.bookings(id) ON DELETE CASCADE,
    stay_id UUID REFERENCES public.stays(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    CONSTRAINT chk_conversation_link CHECK (
        (booking_id IS NOT NULL AND stay_id IS NULL) OR 
        (booking_id IS NULL AND stay_id IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_conversations_booking_id ON public.conversations (booking_id);
CREATE INDEX IF NOT EXISTS idx_conversations_stay_id ON public.conversations (stay_id);

CREATE TRIGGER conversations_updated_at 
  BEFORE UPDATE ON public.conversations 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

CREATE TABLE public.messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id UUID REFERENCES public.conversations(id) ON DELETE CASCADE NOT NULL,
    sender_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON public.messages (conversation_id);
CREATE INDEX IF NOT EXISTS idx_messages_sender_id ON public.messages (sender_id);

ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Conversations Policies
CREATE POLICY "Users can access their booking conversations" ON public.conversations
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.bookings b
      WHERE b.id = conversations.booking_id
      AND (b.guest_id = auth.uid() OR public.is_listing_owner(b.listing_id) OR public.is_admin())
    )
  );

CREATE POLICY "Users can access their stay conversations" ON public.conversations
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.stays s
      WHERE s.id = conversations.stay_id
      AND (s.guest_id = auth.uid() OR public.is_listing_owner(s.listing_id) OR public.is_admin())
    )
  );

CREATE POLICY "Users can insert conversations" ON public.conversations
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.bookings b
      WHERE b.id = conversations.booking_id
      AND (b.guest_id = auth.uid() OR public.is_listing_owner(b.listing_id) OR public.is_admin())
    ) OR EXISTS (
      SELECT 1 FROM public.stays s
      WHERE s.id = conversations.stay_id
      AND (s.guest_id = auth.uid() OR public.is_listing_owner(s.listing_id) OR public.is_admin())
    )
  );

-- Messages Policies
CREATE POLICY "Users can read messages in their conversations" ON public.messages
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.conversations c
      LEFT JOIN public.bookings b ON b.id = c.booking_id
      LEFT JOIN public.stays s ON s.id = c.stay_id
      WHERE c.id = messages.conversation_id
      AND (
        b.guest_id = auth.uid() OR public.is_listing_owner(b.listing_id) OR
        s.guest_id = auth.uid() OR public.is_listing_owner(s.listing_id) OR
        public.is_admin()
      )
    )
  );

CREATE POLICY "Users can post messages to their conversations" ON public.messages
  FOR INSERT WITH CHECK (
    sender_id = auth.uid() AND
    EXISTS (
      SELECT 1 FROM public.conversations c
      LEFT JOIN public.bookings b ON b.id = c.booking_id
      LEFT JOIN public.stays s ON s.id = c.stay_id
      WHERE c.id = messages.conversation_id
      AND (
        b.guest_id = auth.uid() OR public.is_listing_owner(b.listing_id) OR
        s.guest_id = auth.uid() OR public.is_listing_owner(s.listing_id) OR
        public.is_admin()
      )
    )
  );


-- SOURCE: 15_calendar_sync.sql
/*
==================================================
Domain: Calendar Sync & Automations
Purpose: Manage iCal feeds, external synchronization blocks, and pg_cron scheduled tasks.
Contains: 
- ical_feeds
- external_calendar_events
- triggers & RLS policies
- pg_cron sync scheduling
==================================================
*/

CREATE TABLE public.ical_feeds (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    listing_id UUID REFERENCES public.listings(id) ON DELETE CASCADE NOT NULL,
    feed_url TEXT NOT NULL,
    provider TEXT NOT NULL,
    enabled BOOLEAN DEFAULT true NOT NULL,
    sync_direction public.sync_direction DEFAULT 'import'::public.sync_direction NOT NULL,
    last_synced_at TIMESTAMPTZ,
    last_success_at TIMESTAMPTZ,
    last_error TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE INDEX IF NOT EXISTS ical_feeds_listing_idx ON public.ical_feeds(listing_id);

CREATE TRIGGER ical_feeds_updated_at 
  BEFORE UPDATE ON public.ical_feeds 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

ALTER TABLE public.ical_feeds ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Hosts can manage their ical feeds" ON public.ical_feeds
  FOR ALL USING (public.is_listing_owner(listing_id) OR public.is_admin());

CREATE TABLE public.external_calendar_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    feed_id UUID REFERENCES public.ical_feeds(id) ON DELETE CASCADE NOT NULL,
    external_uid TEXT NOT NULL,
    listing_id UUID REFERENCES public.listings(id) ON DELETE CASCADE NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    summary TEXT,
    last_seen_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    UNIQUE(feed_id, external_uid)
);

CREATE INDEX IF NOT EXISTS external_events_listing_date_idx ON public.external_calendar_events(listing_id, start_date, end_date);

CREATE TRIGGER external_calendar_events_updated_at 
  BEFORE UPDATE ON public.external_calendar_events 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

ALTER TABLE public.external_calendar_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Hosts can view their external events" ON public.external_calendar_events
  FOR SELECT USING (public.is_listing_owner(listing_id) OR public.is_admin());

CREATE POLICY "Hosts can manage their external events" ON public.external_calendar_events
  FOR ALL USING (public.is_listing_owner(listing_id) OR public.is_admin());

-- Schedule pg_cron sync job (Replace URLs and keys with actual environment values in deployment)
SELECT cron.schedule(
    'sync-ical-hourly',
    '0 * * * *',
    $$
    SELECT net.http_post(
        url:='YOUR_SUPABASE_PROJECT_URL/functions/v1/sync-ical',
        headers:='{"Content-Type": "application/json", "Authorization": "Bearer YOUR_ANON_KEY"}'::jsonb
    );
    $$
);


-- SOURCE: 16_storage_buckets.sql
/*
==================================================
Domain: Storage Buckets
Purpose: Configures Supabase object storage buckets and storage access RLS policies.
Contains: 
- Storage bucket definitions (listings, avatars)
- Storage policies for object management
==================================================
*/

INSERT INTO storage.buckets (id, name, public, file_size_limit) 
VALUES 
  ('listings', 'listings', true, 2097152),
  ('avatars', 'avatars', true, 3145728)
ON CONFLICT (id) DO UPDATE SET 
  file_size_limit = EXCLUDED.file_size_limit,
  public = EXCLUDED.public;

DROP POLICY IF EXISTS "Public Access Listings" ON storage.objects;
DROP POLICY IF EXISTS "Public Access Avatars" ON storage.objects;
DROP POLICY IF EXISTS "Auth Upload Listings" ON storage.objects;
DROP POLICY IF EXISTS "Auth Upload Avatars" ON storage.objects;
DROP POLICY IF EXISTS "Users update own avatars" ON storage.objects;
DROP POLICY IF EXISTS "Hosts update own listing photos" ON storage.objects;

-- Allow public to read objects
CREATE POLICY "Public Access Listings" ON storage.objects FOR SELECT 
USING (bucket_id = 'listings');

CREATE POLICY "Public Access Avatars" ON storage.objects FOR SELECT 
USING (bucket_id = 'avatars');

-- Allow authenticated users to upload
CREATE POLICY "Auth Upload Listings" ON storage.objects FOR INSERT 
WITH CHECK (bucket_id = 'listings' AND auth.role() = 'authenticated');

CREATE POLICY "Auth Upload Avatars" ON storage.objects FOR INSERT 
WITH CHECK (bucket_id = 'avatars' AND auth.role() = 'authenticated');

-- Allow authenticated users to update/delete their uploaded objects
CREATE POLICY "Users modify own avatars" ON storage.objects FOR ALL
USING (bucket_id = 'avatars' AND auth.uid() = owner);

CREATE POLICY "Users modify own listing photos" ON storage.objects FOR ALL
USING (bucket_id = 'listings' AND auth.uid() = owner);


-- SOURCE: 17_search_functions.sql
/*
==================================================
Domain: Search & Discovery
Purpose: Discovery RPCs, indexing queries, and detailed listing view models.
Contains: 
- get_listing_detail RPC
- search_listings RPC
==================================================
*/

CREATE OR REPLACE FUNCTION public.get_listing_detail(p_public_id TEXT)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    result JSON;
BEGIN
    SELECT row_to_json(l_data) INTO result
    FROM (
        SELECT 
            l.id,
            l.public_id,
            l.title,
            l.description,
            l.status,
            l.furnishing,
            l.gender_preference,
            l.occupancy_type,
            l.created_at,
            l.state,
            l.city,
            l.locality,
            l.postal_code,
            l.latitude,
            l.longitude,
            l.formatted_address,
            (
                SELECT row_to_json(t)
                FROM (
                    SELECT name, description
                    FROM public.accommodation_types
                    WHERE id = l.accommodation_type_id
                ) t
            ) as accommodation_type,
            (
                SELECT row_to_json(h)
                FROM (
                    SELECT 
                        p.id,
                        p.full_name,
                        p.avatar_storage_path as avatar_url,
                        p.created_at
                    FROM public.profiles p
                    WHERE p.id = l.host_id
                ) h
            ) as host,
            (
                SELECT row_to_json(pr)
                FROM (
                    SELECT 
                        amount,
                        currency,
                        billing_period,
                        security_deposit,
                        maintenance_fee,
                        maintenance_fee_period,
                        minimum_duration,
                        maximum_duration
                    FROM public.listing_prices
                    WHERE listing_id = l.id
                ) pr
            ) as pricing,
            (
                SELECT row_to_json(av)
                FROM (
                    SELECT 
                        start_date,
                        available_units,
                        status
                    FROM public.listing_availability
                    WHERE listing_id = l.id
                ) av
            ) as availability,
            (
                SELECT COALESCE(json_agg(row_to_json(img)), '[]'::json)
                FROM (
                    SELECT 
                        storage_path as image_url,
                        display_order,
                        is_cover
                    FROM public.listing_images
                    WHERE listing_id = l.id
                    ORDER BY display_order ASC
                ) img
            ) as images,
            (
                SELECT COALESCE(json_agg(row_to_json(am)), '[]'::json)
                FROM (
                    SELECT 
                        a.name,
                        a.icon
                    FROM public.listing_amenities la
                    JOIN public.amenities a ON a.id = la.amenity_id
                    WHERE la.listing_id = l.id
                ) am
            ) as amenities
        FROM public.listings l
        JOIN public.accommodation_types act ON act.id = l.accommodation_type_id
        JOIN public.listing_prices lpr ON lpr.listing_id = l.id
        WHERE l.public_id = p_public_id
        AND (
            l.status = 'published' 
            OR public.is_listing_owner(l.id) 
            OR public.is_admin()
        )
    ) l_data;

    RETURN result;
END;
$$;


CREATE OR REPLACE FUNCTION public.search_listings(
  p_city TEXT DEFAULT NULL,
  p_locality TEXT DEFAULT NULL,
  p_accommodation_type_id UUID DEFAULT NULL,
  p_furnishing public.furnishing DEFAULT NULL,
  p_gender_preference public.gender_preference DEFAULT NULL,
  p_occupancy_type public.occupancy_type DEFAULT NULL,
  p_billing_period public.billing_period DEFAULT NULL,
  p_amenities TEXT[] DEFAULT NULL,
  p_min_price NUMERIC DEFAULT NULL,
  p_max_price NUMERIC DEFAULT NULL,
  p_available_from DATE DEFAULT NULL,
  p_sort TEXT DEFAULT 'recommended',
  p_page INTEGER DEFAULT 1,
  p_page_size INTEGER DEFAULT 12,
  p_min_lat DOUBLE PRECISION DEFAULT NULL,
  p_max_lat DOUBLE PRECISION DEFAULT NULL,
  p_min_lng DOUBLE PRECISION DEFAULT NULL,
  p_max_lng DOUBLE PRECISION DEFAULT NULL,
  p_center_lat DOUBLE PRECISION DEFAULT NULL,
  p_center_lng DOUBLE PRECISION DEFAULT NULL
)
RETURNS TABLE (
  total_count BIGINT,
  listing_id UUID,
  public_id TEXT,
  title TEXT,
  accommodation_type_name TEXT,
  furnishing public.furnishing,
  gender_preference public.gender_preference,
  occupancy_type public.occupancy_type,
  locality TEXT,
  city TEXT,
  formatted_address TEXT,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  price_amount NUMERIC,
  price_currency TEXT,
  price_billing_period public.billing_period,
  price_minimum_duration INTEGER,
  image_url TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_offset INTEGER;
BEGIN
  -- Clamp pagination values
  IF p_page < 1 THEN p_page := 1; END IF;
  IF p_page_size < 1 THEN p_page_size := 12; END IF;
  IF p_page_size > 48 THEN p_page_size := 48; END IF;

  v_offset := (p_page - 1) * p_page_size;

  RETURN QUERY
  SELECT
    COUNT(*) OVER() AS total_count,
    l.id AS listing_id,
    l.public_id,
    l.title,
    at.name AS accommodation_type_name,
    l.furnishing,
    l.gender_preference,
    l.occupancy_type,
    l.locality,
    l.city,
    l.formatted_address,
    l.latitude,
    l.longitude,
    lp.amount AS price_amount,
    lp.currency AS price_currency,
    lp.billing_period AS price_billing_period,
    lp.minimum_duration AS price_minimum_duration,
    (
      SELECT li.storage_path
      FROM public.listing_images li
      WHERE li.listing_id = l.id
      ORDER BY li.is_cover DESC, li.display_order ASC
      LIMIT 1
    ) AS image_url
  FROM public.listings l
  JOIN public.accommodation_types at ON at.id = l.accommodation_type_id
  JOIN public.listing_prices lp ON lp.listing_id = l.id
  WHERE
    -- Only published listings
    l.status = 'published'

    -- Location text filters
    AND (p_city IS NULL OR l.city ILIKE p_city)
    AND (p_locality IS NULL OR l.locality ILIKE p_locality)

    -- Map bounding box filters
    AND (p_min_lat IS NULL OR l.latitude >= p_min_lat)
    AND (p_max_lat IS NULL OR l.latitude <= p_max_lat)
    AND (p_min_lng IS NULL OR l.longitude >= p_min_lng)
    AND (p_max_lng IS NULL OR l.longitude <= p_max_lng)

    -- Accommodation type filter
    AND (p_accommodation_type_id IS NULL OR l.accommodation_type_id = p_accommodation_type_id)

    -- Property attribute filters
    AND (p_furnishing IS NULL OR l.furnishing = p_furnishing)
    AND (p_gender_preference IS NULL OR l.gender_preference = p_gender_preference)
    AND (p_occupancy_type IS NULL OR l.occupancy_type = p_occupancy_type)

    -- Billing period filter
    AND (p_billing_period IS NULL OR lp.billing_period = p_billing_period)

    -- Price range filters
    AND (p_min_price IS NULL OR lp.amount >= p_min_price)
    AND (p_max_price IS NULL OR lp.amount <= p_max_price)

    -- Availability filter
    AND (
      p_available_from IS NULL
      OR EXISTS (
        SELECT 1 FROM public.listing_availability la
        WHERE la.listing_id = l.id
          AND la.status = 'available'
          AND la.start_date <= p_available_from
      )
    )

    -- Amenities filter
    AND (
      p_amenities IS NULL
      OR array_length(p_amenities, 1) IS NULL
      OR NOT EXISTS (
        SELECT unnest(p_amenities)
        EXCEPT
        SELECT a.name
        FROM public.listing_amenities la2
        JOIN public.amenities a ON a.id = la2.amenity_id
        WHERE la2.listing_id = l.id
      )
    )

  ORDER BY
    -- Distance sorting using Haversine formula
    CASE WHEN p_sort = 'distance' AND p_center_lat IS NOT NULL AND p_center_lng IS NOT NULL THEN
      6371 * acos(
        cos(radians(p_center_lat)) * cos(radians(l.latitude)) *
        cos(radians(l.longitude) - radians(p_center_lng)) +
        sin(radians(p_center_lat)) * sin(radians(l.latitude))
      )
    END ASC NULLS LAST,
    CASE WHEN p_sort = 'price_asc' THEN lp.amount END ASC NULLS LAST,
    CASE WHEN p_sort = 'price_desc' THEN lp.amount END DESC NULLS LAST,
    CASE WHEN p_sort = 'newest' THEN l.created_at END DESC,
    CASE WHEN p_sort = 'recommended' OR (p_sort NOT IN ('price_asc', 'price_desc', 'newest', 'distance')) THEN l.created_at END DESC

  LIMIT p_page_size
  OFFSET v_offset;
END;
$$;


-- SOURCE: 18_seed_reference_data.sql
/*
==================================================
Domain: Seed Reference Data
Purpose: Initialize master reference data (accommodation types, amenities, geography).
NOTE: No demo or fake user/listing data is seeded here.
==================================================
*/

-- 1. Insert Accommodation Types
INSERT INTO public.accommodation_types (id, name, description) VALUES
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'PG', 'Paying Guest accommodation'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'Hostel', 'Shared hostel accommodation'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'Apartment', 'Standard residential apartment'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a14', 'Independent House', 'Standalone house or bungalow'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a15', 'Villa', 'Luxury standalone villa'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a16', 'Private Room', 'Private room within a shared property'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a17', 'Shared Room', 'Shared room with other occupants'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a18', 'Service Apartment', 'Furnished apartment with hotel-like services'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a19', 'Co-living', 'Modern managed shared living spaces')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;

-- 2. Insert Amenities
-- Essentials
INSERT INTO public.amenities (id, name, icon) VALUES
  ('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b11', 'Wi-Fi', 'wifi'),
  ('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b12', 'Electricity', 'zap'),
  ('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b13', 'Water', 'droplets')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon;

-- Comfort
INSERT INTO public.amenities (id, name, icon) VALUES
  ('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b14', 'AC', 'snowflake'),
  ('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b15', 'Geyser', 'thermometer'),
  ('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b16', 'Refrigerator', 'refrigerator')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon;

-- Services
INSERT INTO public.amenities (id, name, icon) VALUES
  ('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b17', 'Laundry', 'shirt'),
  ('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b18', 'Housekeeping', 'broom'),
  ('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b19', 'Meals', 'utensils')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon;

-- Security
INSERT INTO public.amenities (id, name, icon) VALUES
  ('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b20', 'CCTV', 'camera'),
  ('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b21', 'Security Guard', 'shield'),
  ('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b22', 'Biometric Entry', 'fingerprint')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon;

-- Parking
INSERT INTO public.amenities (id, name, icon) VALUES
  ('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b23', 'Bike Parking', 'bike'),
  ('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b24', 'Car Parking', 'car')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon;

-- 3. Seed Country: India
INSERT INTO public.countries (external_code, name, iso2, iso3, currency_code, phone_code, timezone_default)
VALUES ('IN', 'India', 'IN', 'IND', 'INR', '+91', 'Asia/Kolkata')
ON CONFLICT (external_code) DO NOTHING;

DO $$
DECLARE
    in_id BIGINT;
    ka_id BIGINT;
    mh_id BIGINT;
    dl_id BIGINT;
    tg_id BIGINT;
BEGIN
    SELECT id INTO in_id FROM public.countries WHERE external_code = 'IN';
    IF in_id IS NULL THEN
        RETURN;
    END IF;

    -- 4. Seed States
    INSERT INTO public.states (country_id, external_code, name, code, slug) VALUES
        (in_id, 'IN-AN', 'Andaman and Nicobar Islands', 'AN', 'andaman-and-nicobar-islands'),
        (in_id, 'IN-AP', 'Andhra Pradesh', 'AP', 'andhra-pradesh'),
        (in_id, 'IN-AR', 'Arunachal Pradesh', 'AR', 'arunachal-pradesh'),
        (in_id, 'IN-AS', 'Assam', 'AS', 'assam'),
        (in_id, 'IN-BR', 'Bihar', 'BR', 'bihar'),
        (in_id, 'IN-CH', 'Chandigarh', 'CH', 'chandigarh'),
        (in_id, 'IN-CT', 'Chhattisgarh', 'CT', 'chhattisgarh'),
        (in_id, 'IN-DN', 'Dadra and Nagar Haveli and Daman and Diu', 'DN', 'dadra-and-nagar-haveli-and-daman-and-diu'),
        (in_id, 'IN-DL', 'Delhi', 'DL', 'delhi'),
        (in_id, 'IN-GA', 'Goa', 'GA', 'goa'),
        (in_id, 'IN-GJ', 'Gujarat', 'GJ', 'gujarat'),
        (in_id, 'IN-HR', 'Haryana', 'HR', 'haryana'),
        (in_id, 'IN-HP', 'Himachal Pradesh', 'HP', 'himachal-pradesh'),
        (in_id, 'IN-JK', 'Jammu and Kashmir', 'JK', 'jammu-and-kashmir'),
        (in_id, 'IN-JH', 'Jharkhand', 'JH', 'jharkhand'),
        (in_id, 'IN-KA', 'Karnataka', 'KA', 'karnataka'),
        (in_id, 'IN-KL', 'Kerala', 'KL', 'kerala'),
        (in_id, 'IN-LA', 'Ladakh', 'LA', 'ladakh'),
        (in_id, 'IN-LD', 'Lakshadweep', 'LD', 'lakshadweep'),
        (in_id, 'IN-MP', 'Madhya Pradesh', 'MP', 'madhya-pradesh'),
        (in_id, 'IN-MH', 'Maharashtra', 'MH', 'maharashtra'),
        (in_id, 'IN-MN', 'Manipur', 'MN', 'manipur'),
        (in_id, 'IN-ML', 'Meghalaya', 'ML', 'meghalaya'),
        (in_id, 'IN-MZ', 'Mizoram', 'MZ', 'mizoram'),
        (in_id, 'IN-NL', 'Nagaland', 'NL', 'nagaland'),
        (in_id, 'IN-OR', 'Odisha', 'OR', 'odisha'),
        (in_id, 'IN-PY', 'Puducherry', 'PY', 'puducherry'),
        (in_id, 'IN-PB', 'Punjab', 'PB', 'punjab'),
        (in_id, 'IN-RJ', 'Rajasthan', 'RJ', 'rajasthan'),
        (in_id, 'IN-SK', 'Sikkim', 'SK', 'sikkim'),
        (in_id, 'IN-TN', 'Tamil Nadu', 'TN', 'tamil-nadu'),
        (in_id, 'IN-TG', 'Telangana', 'TG', 'telangana'),
        (in_id, 'IN-TR', 'Tripura', 'TR', 'tripura'),
        (in_id, 'IN-UP', 'Uttar Pradesh', 'UP', 'uttar-pradesh'),
        (in_id, 'IN-UT', 'Uttarakhand', 'UT', 'uttarakhand'),
        (in_id, 'IN-WB', 'West Bengal', 'WB', 'west-bengal')
    ON CONFLICT (external_code) DO NOTHING;

    SELECT id INTO ka_id FROM public.states WHERE external_code = 'IN-KA';
    SELECT id INTO mh_id FROM public.states WHERE external_code = 'IN-MH';
    SELECT id INTO dl_id FROM public.states WHERE external_code = 'IN-DL';
    SELECT id INTO tg_id FROM public.states WHERE external_code = 'IN-TG';

    -- 5. Seed Featured Cities
    INSERT INTO public.cities (state_id, external_code, name, search_aliases, slug, latitude, longitude, timezone, is_capital, is_metro, is_featured, sort_order) VALUES
        (ka_id, 'IN-BLR', 'Bangalore', '{"Bengaluru"}', 'bangalore', 12.9716, 77.5946, 'Asia/Kolkata', true, true, true, 1),
        (mh_id, 'IN-BOM', 'Mumbai', '{"Bombay"}', 'mumbai', 19.0760, 72.8777, 'Asia/Kolkata', true, true, true, 2),
        (dl_id, 'IN-DEL', 'New Delhi', '{"Delhi"}', 'new-delhi', 28.6139, 77.2090, 'Asia/Kolkata', true, true, true, 3),
        (tg_id, 'IN-HYD', 'Hyderabad', '{}', 'hyderabad', 17.3850, 78.4867, 'Asia/Kolkata', true, true, true, 4),
        (mh_id, 'IN-PUN', 'Pune', '{"Poona"}', 'pune', 18.5204, 73.8567, 'Asia/Kolkata', false, true, true, 5)
    ON CONFLICT (external_code) DO NOTHING;
END $$;


