-- THIS FILE IS AUTOGENERATED FROM supabase/schema/ DO NOT EDIT DIRECTLY

-- SOURCE: 00_extensions.sql
/*
==================================================
Domain: Extensions
Purpose: Enables PostgreSQL features required for the database.
Contains: 
- uuid-ossp
- pgcrypto
==================================================
*/

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";


-- SOURCE: 01_types.sql
/*
==================================================
Domain: Types
Purpose: Defines shared types and enums used across all domains.
Contains: 
- user_role
- listing_status
- booking_status
- stay_status
- billing_period
- availability_status
- occupancy_type
- gender_preference
- furnishing
==================================================
*/

CREATE TYPE public.user_role AS ENUM ('guest', 'host', 'admin');
CREATE TYPE public.listing_status AS ENUM ('draft', 'ready', 'pending_review', 'published', 'paused', 'archived');
CREATE TYPE public.booking_status AS ENUM ('pending', 'approved', 'rejected', 'cancelled', 'expired');
CREATE TYPE public.stay_status AS ENUM ('upcoming', 'active', 'extended', 'checked_out', 'completed', 'terminated');
CREATE TYPE public.billing_period AS ENUM ('day', 'week', 'month', 'semester', 'year');
CREATE TYPE public.availability_status AS ENUM ('available', 'occupied', 'unavailable');
CREATE TYPE public.occupancy_type AS ENUM ('private', 'shared', 'mixed');
CREATE TYPE public.gender_preference AS ENUM ('any', 'male', 'female');
CREATE TYPE public.furnishing AS ENUM ('unfurnished', 'semi_furnished', 'fully_furnished');


-- SOURCE: 15_shared.sql
/*
==================================================
Domain: Shared
Purpose: Cross-cutting utilities and shared functions.
Contains: 
- updated_at trigger helper
- public_id generator
==================================================
*/

CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.generate_public_id()
RETURNS TEXT AS $$
DECLARE
  chars TEXT := 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  result TEXT := '';
  i INTEGER;
BEGIN
  FOR i IN 1..8 LOOP
    result := result || substr(chars, floor(random() * length(chars) + 1)::integer, 1);
  END LOOP;
  RETURN result;
END;
$$ LANGUAGE plpgsql VOLATILE;


-- SOURCE: 02_identity.sql
/*
==================================================
Domain: Identity
Purpose: Everything related to users.
Contains: 
- profiles
- identity triggers
- identity functions
- identity RLS
==================================================
*/

CREATE TABLE public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    display_name TEXT,
    full_name TEXT,
    avatar_path TEXT,
    bio TEXT,
    city TEXT,
    date_of_birth DATE,
    gender TEXT,
    phone TEXT,
    role public.user_role DEFAULT 'guest'::public.user_role NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own profile" ON public.profiles
  FOR SELECT USING (auth.uid() = id OR public.is_admin());

CREATE POLICY "Users can update own profile" ON public.profiles
  FOR UPDATE USING (auth.uid() = id OR public.is_admin());

-- Protect identity fields
CREATE OR REPLACE FUNCTION public.protect_identity_fields()
RETURNS TRIGGER AS $$
BEGIN
  IF NOT public.is_admin() THEN
    NEW.id = OLD.id;
    NEW.role = OLD.role;
    NEW.created_at = OLD.created_at;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER enforce_profile_immutability
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE PROCEDURE public.protect_identity_fields();

-- Handle new user
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (
    id, 
    full_name, 
    avatar_path, 
    role,
    created_at,
    updated_at
  ) VALUES (
    NEW.id, 
    NEW.raw_user_meta_data->>'full_name', 
    NEW.raw_user_meta_data->>'avatar_path', 
    'guest'::public.user_role,
    NOW(),
    NOW()
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

CREATE TRIGGER profiles_updated_at 
  BEFORE UPDATE ON public.profiles 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- Identity helper functions
CREATE OR REPLACE FUNCTION public.is_host()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN (
    SELECT role = 'host'::public.user_role 
    FROM public.profiles 
    WHERE id = auth.uid()
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN (
    SELECT role = 'admin'::public.user_role 
    FROM public.profiles 
    WHERE id = auth.uid()
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- SOURCE: 04_accommodations.sql
/*
==================================================
Domain: Accommodations
Purpose: Reference entities describing properties.
Contains: 
- accommodation_types
- amenities
==================================================
*/

CREATE TABLE public.accommodation_types (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT UNIQUE NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE public.amenities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT UNIQUE NOT NULL,
    icon TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

ALTER TABLE public.accommodation_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.amenities ENABLE ROW LEVEL SECURITY;

CREATE TRIGGER accommodation_types_updated_at 
  BEFORE UPDATE ON public.accommodation_types 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

CREATE TRIGGER amenities_updated_at 
  BEFORE UPDATE ON public.amenities 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- RLS Policies
CREATE POLICY "Public can view accommodation types" ON public.accommodation_types
  FOR SELECT USING (true);

CREATE POLICY "Public can view amenities" ON public.amenities
  FOR SELECT USING (true);


-- SOURCE: 05_listings.sql
/*
==================================================
Domain: Listings
Purpose: Core marketplace domain for property listings.
Contains: 
- listings
- listing_amenities
- listing_build_progress
- listings triggers
- listings RLS
==================================================
*/

CREATE TABLE public.listings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    public_id TEXT UNIQUE NOT NULL DEFAULT public.generate_public_id(),
    host_id UUID REFERENCES public.profiles(id) ON DELETE RESTRICT NOT NULL,
    accommodation_type_id UUID REFERENCES public.accommodation_types(id) ON DELETE RESTRICT NOT NULL,
    property_type TEXT DEFAULT 'Apartment' NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    max_occupants INTEGER DEFAULT 1 NOT NULL,
    occupancy_type public.occupancy_type DEFAULT 'private'::public.occupancy_type NOT NULL,
    gender_preference public.gender_preference DEFAULT 'any'::public.gender_preference NOT NULL,
    furnishing public.furnishing DEFAULT 'unfurnished'::public.furnishing NOT NULL,
    
    -- Location Fields
    country_code TEXT,
    country TEXT,
    state TEXT,
    city TEXT,
    locality TEXT,
    postal_code TEXT,
    latitude NUMERIC,
    longitude NUMERIC,
    formatted_address TEXT,
    
    status public.listing_status DEFAULT 'draft'::public.listing_status NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE INDEX idx_listings_public_id ON public.listings(public_id);
CREATE INDEX idx_listings_host_id ON public.listings(host_id);

CREATE TABLE public.listing_amenities (
    listing_id UUID REFERENCES public.listings(id) ON DELETE CASCADE NOT NULL,
    amenity_id UUID REFERENCES public.amenities(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    PRIMARY KEY (listing_id, amenity_id)
);

CREATE TABLE public.listing_build_progress (
    listing_id UUID PRIMARY KEY REFERENCES public.listings(id) ON DELETE CASCADE,
    step_completed TEXT,
    last_step TEXT NOT NULL DEFAULT 'accommodation',
    percent_complete INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Triggers
CREATE TRIGGER listings_updated_at 
  BEFORE UPDATE ON public.listings 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

CREATE TRIGGER listing_amenities_updated_at 
  BEFORE UPDATE ON public.listing_amenities 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

CREATE TRIGGER listing_build_progress_updated_at 
  BEFORE UPDATE ON public.listing_build_progress 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- RLS
ALTER TABLE public.listings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.listing_amenities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.listing_build_progress ENABLE ROW LEVEL SECURITY;

-- Listings Policies
CREATE POLICY "Public can read published listings" ON public.listings
  FOR SELECT USING (status = 'published'::public.listing_status OR host_id = auth.uid() OR public.is_admin());

CREATE POLICY "Hosts can insert listings" ON public.listings
  FOR INSERT WITH CHECK (
    auth.uid() IS NOT NULL AND 
    (public.is_host() OR public.is_admin()) AND
    host_id = auth.uid()
  );

CREATE POLICY "Hosts can update own listings" ON public.listings
  FOR UPDATE USING (host_id = auth.uid() OR public.is_admin());

CREATE POLICY "Hosts can delete own listings" ON public.listings
  FOR DELETE USING (host_id = auth.uid() OR public.is_admin());

-- Listing Amenities Policies
CREATE POLICY "Public can view listing amenities" ON public.listing_amenities
  FOR SELECT USING (true);

CREATE POLICY "Hosts can manage own listing amenities" ON public.listing_amenities
  FOR ALL USING (
    EXISTS (
        SELECT 1 FROM public.listings l 
        WHERE l.id = listing_amenities.listing_id 
        AND l.host_id = auth.uid()
    )
  );

-- Listing Build Progress Policies
CREATE POLICY "Hosts can view own listing progress" ON public.listing_build_progress
  FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM public.listings l 
        WHERE l.id = listing_build_progress.listing_id 
        AND l.host_id = auth.uid()
    )
  );

CREATE POLICY "Hosts can insert own listing progress" ON public.listing_build_progress
  FOR INSERT WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.listings l 
        WHERE l.id = listing_build_progress.listing_id 
        AND l.host_id = auth.uid()
    )
  );

CREATE POLICY "Hosts can update own listing progress" ON public.listing_build_progress
  FOR UPDATE USING (
    EXISTS (
        SELECT 1 FROM public.listings l 
        WHERE l.id = listing_build_progress.listing_id 
        AND l.host_id = auth.uid()
    )
  );

CREATE POLICY "Hosts can delete own listing progress" ON public.listing_build_progress
  FOR DELETE USING (
    EXISTS (
        SELECT 1 FROM public.listings l 
        WHERE l.id = listing_build_progress.listing_id 
        AND l.host_id = auth.uid()
    )
  );


-- SOURCE: 06_listing_images.sql
/*
==================================================
Domain: Listing Images
Purpose: Dedicated domain for property images.
Contains: 
- listing_images
- triggers
- RLS
==================================================
*/

CREATE TABLE public.listing_images (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    listing_id UUID REFERENCES public.listings(id) ON DELETE CASCADE NOT NULL,
    storage_path TEXT NOT NULL,
    display_order INTEGER DEFAULT 0 NOT NULL,
    is_cover BOOLEAN DEFAULT false,
    file_size INTEGER,
    mime_type TEXT,
    width INTEGER,
    height INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Ensure only one cover image per listing
CREATE UNIQUE INDEX idx_listing_images_cover 
  ON public.listing_images (listing_id) 
  WHERE is_cover = true;

CREATE INDEX idx_listing_images_listing_id ON public.listing_images(listing_id);

CREATE TRIGGER listing_images_updated_at 
  BEFORE UPDATE ON public.listing_images 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

ALTER TABLE public.listing_images ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view listing images" ON public.listing_images
  FOR SELECT USING (true);

CREATE POLICY "Hosts can manage own listing images" ON public.listing_images
  FOR ALL USING (
    EXISTS (
        SELECT 1 FROM public.listings l 
        WHERE l.id = listing_images.listing_id 
        AND l.host_id = auth.uid()
    )
  );


-- SOURCE: 07_pricing.sql
/*
==================================================
Domain: Pricing
Purpose: Anything financial related to listings.
Contains: 
- listing_prices
- triggers
- RLS
==================================================
*/

CREATE TABLE public.listing_prices (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    listing_id UUID REFERENCES public.listings(id) ON DELETE CASCADE NOT NULL UNIQUE,
    amount NUMERIC(12, 2) NOT NULL,
    currency TEXT DEFAULT 'INR' NOT NULL,
    billing_period public.billing_period NOT NULL,
    security_deposit NUMERIC(12, 2) DEFAULT 0 NOT NULL,
    maintenance_fee NUMERIC(12, 2) DEFAULT 0 NOT NULL,
    maintenance_fee_period public.billing_period,
    minimum_duration INTEGER DEFAULT 1 NOT NULL,
    maximum_duration INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TRIGGER listing_prices_updated_at 
  BEFORE UPDATE ON public.listing_prices 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

ALTER TABLE public.listing_prices ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view listing prices" ON public.listing_prices
  FOR SELECT USING (true);

CREATE POLICY "Hosts can manage own listing prices" ON public.listing_prices
  FOR ALL USING (
    EXISTS (
        SELECT 1 FROM public.listings l 
        WHERE l.id = listing_prices.listing_id 
        AND l.host_id = auth.uid()
    )
  );


-- SOURCE: 09_bookings.sql
/*
==================================================
Domain: Bookings
Purpose: Booking lifecycle and requests.
Contains: 
- bookings
- booking_events
- triggers
- RLS
==================================================
*/

CREATE TABLE public.bookings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    listing_id UUID REFERENCES public.listings(id) ON DELETE RESTRICT NOT NULL,
    guest_id UUID REFERENCES public.profiles(id) ON DELETE RESTRICT NOT NULL,
    requested_move_in DATE NOT NULL,
    requested_duration INTEGER NOT NULL,
    message TEXT,
    snapshot_monthly_rent NUMERIC(12, 2) NOT NULL,
    snapshot_security_deposit NUMERIC(12, 2) NOT NULL,
    snapshot_maintenance_fee NUMERIC(12, 2) NOT NULL,
    snapshot_billing_period public.billing_period NOT NULL,
    snapshot_minimum_stay INTEGER NOT NULL,
    expires_at TIMESTAMPTZ,
    status public.booking_status DEFAULT 'pending'::public.booking_status NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE public.booking_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id UUID REFERENCES public.bookings(id) ON DELETE CASCADE NOT NULL,
    event_type TEXT NOT NULL,
    actor_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    metadata JSONB DEFAULT '{}'::jsonb NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TRIGGER bookings_updated_at 
  BEFORE UPDATE ON public.bookings 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.booking_events ENABLE ROW LEVEL SECURITY;

-- Bookings RLS
CREATE POLICY "Guests can view own bookings" ON public.bookings
  FOR SELECT USING (guest_id = auth.uid() OR public.is_admin());

CREATE POLICY "Hosts can view bookings for their listings" ON public.bookings
  FOR SELECT USING (public.is_listing_owner(listing_id) OR public.is_admin());

CREATE POLICY "Authenticated users can create bookings" ON public.bookings
  FOR INSERT WITH CHECK (
    auth.uid() IS NOT NULL AND guest_id = auth.uid()
  );

CREATE POLICY "Guests can cancel pending bookings" ON public.bookings
  FOR UPDATE USING (guest_id = auth.uid() AND status = 'pending'::public.booking_status)
  WITH CHECK (guest_id = auth.uid() AND status = 'cancelled'::public.booking_status);

CREATE POLICY "Hosts can approve or reject pending bookings" ON public.bookings
  FOR UPDATE USING (public.is_listing_owner(listing_id) AND status = 'pending'::public.booking_status)
  WITH CHECK (public.is_listing_owner(listing_id) AND status IN ('approved'::public.booking_status, 'rejected'::public.booking_status));

CREATE POLICY "Admins can update all bookings" ON public.bookings
  FOR UPDATE USING (public.is_admin());

CREATE POLICY "Admins can delete bookings" ON public.bookings
  FOR DELETE USING (public.is_admin());

-- Booking Events RLS
CREATE POLICY "Guests can view own booking events" ON public.booking_events
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.bookings b 
      WHERE b.id = booking_events.booking_id 
      AND b.guest_id = auth.uid()
    ) OR public.is_admin()
  );

CREATE POLICY "Hosts can view booking events for their listings" ON public.booking_events
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.bookings b 
      WHERE b.id = booking_events.booking_id 
      AND public.is_listing_owner(b.listing_id)
    ) OR public.is_admin()
  );

CREATE POLICY "Actors can insert booking events" ON public.booking_events
  FOR INSERT WITH CHECK (
    auth.uid() IS NOT NULL AND actor_id = auth.uid()
  );


-- SOURCE: 10_stays.sql
/*
==================================================
Domain: Stays
Purpose: Track actual tenancy or active bookings.
Contains: 
- stays
- triggers
- RLS
==================================================
*/

CREATE TABLE public.stays (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    listing_id UUID REFERENCES public.listings(id) ON DELETE RESTRICT NOT NULL,
    guest_id UUID REFERENCES public.profiles(id) ON DELETE RESTRICT NOT NULL,
    created_from_booking_id UUID REFERENCES public.bookings(id) ON DELETE SET NULL,
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    expected_move_in_date DATE NOT NULL,
    actual_move_in_date DATE,
    expected_move_out_date DATE NOT NULL,
    actual_move_out_date DATE,
    agreed_amount NUMERIC(12, 2) NOT NULL,
    agreed_billing_period public.billing_period NOT NULL,
    security_deposit_paid NUMERIC(12, 2) DEFAULT 0 NOT NULL,
    status public.stay_status DEFAULT 'upcoming'::public.stay_status NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TRIGGER stays_updated_at 
  BEFORE UPDATE ON public.stays 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

ALTER TABLE public.stays ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Guests can view own stays" ON public.stays
  FOR SELECT USING (guest_id = auth.uid() OR public.is_admin());

CREATE POLICY "Hosts can view stays for their listings" ON public.stays
  FOR SELECT USING (public.is_listing_owner(listing_id) OR public.is_admin());

CREATE POLICY "Hosts can manage stays" ON public.stays
  FOR ALL USING (public.is_listing_owner(listing_id) OR public.is_admin());


-- SOURCE: 11_reviews.sql
/*
==================================================
Domain: Reviews
Purpose: Guest and host feedback.
Contains: 
- reviews
- triggers
- RLS
==================================================
*/

CREATE TABLE public.reviews (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    listing_id UUID REFERENCES public.listings(id) ON DELETE RESTRICT NOT NULL,
    stay_id UUID REFERENCES public.stays(id) ON DELETE RESTRICT NOT NULL UNIQUE,
    guest_id UUID REFERENCES public.profiles(id) ON DELETE RESTRICT NOT NULL,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    host_response TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TRIGGER reviews_updated_at 
  BEFORE UPDATE ON public.reviews 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view reviews" ON public.reviews
  FOR SELECT USING (true);

CREATE POLICY "Guests can create reviews for their stays" ON public.reviews
  FOR INSERT WITH CHECK (
    auth.uid() IS NOT NULL AND 
    guest_id = auth.uid() AND
    EXISTS (
        SELECT 1 FROM public.stays s 
        WHERE s.id = reviews.stay_id 
        AND s.guest_id = auth.uid()
        AND s.status = 'completed'::public.stay_status
    )
  );

CREATE POLICY "Guests can update own reviews" ON public.reviews
  FOR UPDATE USING (guest_id = auth.uid() OR public.is_admin());

CREATE POLICY "Hosts can respond to reviews" ON public.reviews
  FOR UPDATE USING (
    EXISTS (
        SELECT 1 FROM public.listings l 
        WHERE l.id = reviews.listing_id 
        AND l.host_id = auth.uid()
    )
  );

CREATE POLICY "Admins can manage all reviews" ON public.reviews
  FOR ALL USING (public.is_admin());


-- SOURCE: 12_notifications.sql
/*
==================================================
Domain: Notifications
Purpose: Generic in-app notification system.
Contains: 
- notifications
- triggers
- RLS
==================================================
*/

CREATE TABLE public.notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    link TEXT,
    read_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Note: No updated_at trigger because notifications are generally immutable (except for read_at)

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own notifications" ON public.notifications
  FOR SELECT USING (user_id = auth.uid() OR public.is_admin());

CREATE POLICY "Users can update own notifications" ON public.notifications
  FOR UPDATE USING (user_id = auth.uid() OR public.is_admin())
  WITH CHECK (user_id = auth.uid() OR public.is_admin());

CREATE POLICY "System can insert notifications" ON public.notifications
  FOR INSERT WITH CHECK (true); -- Usually inserted via Server Actions, but allows triggers if necessary


-- SOURCE: 13_messaging.sql
/*
==================================================
Domain: Messaging
Purpose: V1 host-guest communication.
Contains: 
- conversations
- messages
- RLS
==================================================
*/

CREATE TABLE public.conversations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id UUID REFERENCES public.bookings(id) ON DELETE SET NULL,
    stay_id UUID REFERENCES public.stays(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    closed_at TIMESTAMPTZ,
    
    CONSTRAINT one_reference_only CHECK (
        (booking_id IS NOT NULL AND stay_id IS NULL) OR 
        (booking_id IS NULL AND stay_id IS NOT NULL)
    )
);

CREATE TABLE public.messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id UUID REFERENCES public.conversations(id) ON DELETE CASCADE NOT NULL,
    sender_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Conversations RLS
-- A user can view a conversation if they are the guest or host associated with the booking or stay
CREATE POLICY "Users can view their conversations" ON public.conversations
  FOR SELECT USING (
    (booking_id IS NOT NULL AND EXISTS (
        SELECT 1 FROM public.bookings b
        JOIN public.listings l ON l.id = b.listing_id
        WHERE b.id = conversations.booking_id
        AND (b.guest_id = auth.uid() OR l.host_id = auth.uid())
    ))
    OR
    (stay_id IS NOT NULL AND EXISTS (
        SELECT 1 FROM public.stays s
        JOIN public.listings l ON l.id = s.listing_id
        WHERE s.id = conversations.stay_id
        AND (s.guest_id = auth.uid() OR l.host_id = auth.uid())
    ))
    OR public.is_admin()
  );

CREATE POLICY "System can create conversations" ON public.conversations
  FOR INSERT WITH CHECK (true); -- Typically created via Server Action

-- Messages RLS
CREATE POLICY "Users can view messages in their conversations" ON public.messages
  FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM public.conversations c
        WHERE c.id = messages.conversation_id
        AND (
            (c.booking_id IS NOT NULL AND EXISTS (
                SELECT 1 FROM public.bookings b
                JOIN public.listings l ON l.id = b.listing_id
                WHERE b.id = c.booking_id
                AND (b.guest_id = auth.uid() OR l.host_id = auth.uid())
            ))
            OR
            (c.stay_id IS NOT NULL AND EXISTS (
                SELECT 1 FROM public.stays s
                JOIN public.listings l ON l.id = s.listing_id
                WHERE s.id = c.stay_id
                AND (s.guest_id = auth.uid() OR l.host_id = auth.uid())
            ))
        )
    )
    OR public.is_admin()
  );

CREATE POLICY "Users can send messages to their conversations" ON public.messages
  FOR INSERT WITH CHECK (
    auth.uid() IS NOT NULL AND sender_id = auth.uid() AND
    EXISTS (
        SELECT 1 FROM public.conversations c
        WHERE c.id = messages.conversation_id
        AND (
            (c.booking_id IS NOT NULL AND EXISTS (
                SELECT 1 FROM public.bookings b
                JOIN public.listings l ON l.id = b.listing_id
                WHERE b.id = c.booking_id
                AND (b.guest_id = auth.uid() OR l.host_id = auth.uid())
            ))
            OR
            (c.stay_id IS NOT NULL AND EXISTS (
                SELECT 1 FROM public.stays s
                JOIN public.listings l ON l.id = s.listing_id
                WHERE s.id = c.stay_id
                AND (s.guest_id = auth.uid() OR l.host_id = auth.uid())
            ))
        )
    )
  );


-- SOURCE: 14_storage.sql
/*
==================================================
Domain: Storage
Purpose: Configures Supabase storage buckets and RLS.
Contains: 
- Storage bucket definitions
- Storage policies
==================================================
*/

INSERT INTO storage.buckets (id, name, public, file_size_limit) 
VALUES 
  ('listings', 'listings', true, 2097152),
  ('avatars', 'avatars', true, 3145728)
ON CONFLICT (id) DO UPDATE SET 
  file_size_limit = EXCLUDED.file_size_limit;

-- Drop existing policies if any to ensure clean state
DROP POLICY IF EXISTS "Public Access Listings" ON storage.objects;
DROP POLICY IF EXISTS "Public Access Avatars" ON storage.objects;
DROP POLICY IF EXISTS "Auth Upload Listings" ON storage.objects;
DROP POLICY IF EXISTS "Auth Upload Avatars" ON storage.objects;

-- Allow public to read objects
CREATE POLICY "Public Access Listings" ON storage.objects FOR SELECT 
USING (bucket_id = 'listings');

CREATE POLICY "Public Access Avatars" ON storage.objects FOR SELECT 
USING (bucket_id = 'avatars');

-- Allow authenticated users to upload
CREATE POLICY "Auth Upload Listings" ON storage.objects FOR INSERT 
WITH CHECK (bucket_id = 'listings' AND auth.role() = 'authenticated');

CREATE POLICY "Auth Upload Avatars" ON storage.objects FOR INSERT 
WITH CHECK (bucket_id = 'avatars' AND auth.role() = 'authenticated');


-- SOURCE: 08_availability.sql
/*
==================================================
Domain: Availability
Purpose: Tracks listing availability dates and host blocks.
Contains: 
- listing_availability
- RLS
==================================================
*/

CREATE TABLE public.listing_availability (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    listing_id UUID REFERENCES public.listings(id) ON DELETE CASCADE NOT NULL,
    available_from DATE NOT NULL,
    available_units INTEGER DEFAULT 1 NOT NULL,
    status public.availability_status DEFAULT 'available'::public.availability_status NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TRIGGER listing_availability_updated_at 
  BEFORE UPDATE ON public.listing_availability 
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

ALTER TABLE public.listing_availability ENABLE ROW LEVEL SECURITY;

-- Availability RLS
CREATE POLICY "Public can view availability" ON public.listing_availability
  FOR SELECT USING (true);

CREATE POLICY "Hosts can manage availability" ON public.listing_availability
  FOR ALL USING (
    EXISTS (
        SELECT 1 FROM public.listings l 
        WHERE l.id = listing_availability.listing_id 
        AND l.host_id = auth.uid()
    )
  );


-- SOURCE: 08_search.sql
/*
==================================================
Domain: Search & Discovery
Purpose: Discovery, indexing, and view models.
Contains: 
- get_listing_detail RPC
- search_listings RPC
==================================================
*/

CREATE OR REPLACE FUNCTION public.get_listing_detail(p_public_id TEXT)
RETURNS JSON AS $$
DECLARE
    result JSON;
BEGIN
    SELECT row_to_json(l_data) INTO result
    FROM (
        SELECT 
            l.id,
            l.public_id,
            l.title,
            l.description,
            l.max_occupants,
            l.status,
            l.furnishing,
            l.gender_preference,
            l.occupancy_type,
            l.created_at,
            l.country_code,
            l.country,
            l.state,
            l.city,
            l.locality,
            l.postal_code,
            l.latitude,
            l.longitude,
            l.formatted_address,
            (
                SELECT row_to_json(t)
                FROM (
                    SELECT name, description
                    FROM public.accommodation_types
                    WHERE id = l.accommodation_type_id
                ) t
            ) as accommodation_type,
            (
                SELECT row_to_json(h)
                FROM (
                    SELECT 
                        p.id,
                        p.full_name,
                        p.avatar_path as avatar_url,
                        p.created_at
                    FROM public.profiles p
                    WHERE p.id = l.host_id
                ) h
            ) as host,
            (
                SELECT row_to_json(pr)
                FROM (
                    SELECT 
                        amount,
                        currency,
                        billing_period,
                        security_deposit,
                        maintenance_fee,
                        maintenance_fee_period,
                        minimum_duration,
                        maximum_duration
                    FROM public.listing_prices
                    WHERE listing_id = l.id
                ) pr
            ) as pricing,
            (
                SELECT row_to_json(av)
                FROM (
                    SELECT 
                        available_from,
                        available_units,
                        status
                    FROM public.listing_availability
                    WHERE listing_id = l.id
                ) av
            ) as availability,
            (
                SELECT COALESCE(json_agg(row_to_json(img)), '[]'::json)
                FROM (
                    SELECT 
                        storage_path as image_url,
                        display_order,
                        is_cover
                    FROM public.listing_images
                    WHERE listing_id = l.id
                    ORDER BY display_order ASC
                ) img
            ) as images,
            (
                SELECT COALESCE(json_agg(row_to_json(am)), '[]'::json)
                FROM (
                    SELECT 
                        a.name,
                        a.icon
                    FROM public.listing_amenities la
                    JOIN public.amenities a ON a.id = la.amenity_id
                    WHERE la.listing_id = l.id
                ) am
            ) as amenities
        FROM public.listings l
        WHERE l.public_id = p_public_id
        AND (
            l.status = 'published' 
            OR public.is_listing_owner(l.id) 
            OR public.is_admin()
        )
    ) l_data;

    RETURN result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


CREATE OR REPLACE FUNCTION public.search_listings(
  p_city TEXT DEFAULT NULL,
  p_locality TEXT DEFAULT NULL,
  p_accommodation_type_id UUID DEFAULT NULL,
  p_furnishing public.furnishing DEFAULT NULL,
  p_gender_preference public.gender_preference DEFAULT NULL,
  p_occupancy_type public.occupancy_type DEFAULT NULL,
  p_billing_period public.billing_period DEFAULT NULL,
  p_amenities TEXT[] DEFAULT NULL,
  p_min_price NUMERIC DEFAULT NULL,
  p_max_price NUMERIC DEFAULT NULL,
  p_available_from DATE DEFAULT NULL,
  p_sort TEXT DEFAULT 'recommended',
  p_page INTEGER DEFAULT 1,
  p_page_size INTEGER DEFAULT 12
)
RETURNS TABLE (
  total_count BIGINT,
  listing_id UUID,
  public_id TEXT,
  title TEXT,
  accommodation_type_name TEXT,
  furnishing public.furnishing,
  gender_preference public.gender_preference,
  occupancy_type public.occupancy_type,
  max_occupants INTEGER,
  locality TEXT,
  city TEXT,
  country TEXT,
  formatted_address TEXT,
  price_amount NUMERIC,
  price_currency TEXT,
  price_billing_period public.billing_period,
  price_minimum_duration INTEGER,
  image_url TEXT
)
AS $$
DECLARE
  v_offset INTEGER;
BEGIN
  -- Clamp pagination values
  IF p_page < 1 THEN p_page := 1; END IF;
  IF p_page_size < 1 THEN p_page_size := 12; END IF;
  IF p_page_size > 48 THEN p_page_size := 48; END IF;

  v_offset := (p_page - 1) * p_page_size;

  RETURN QUERY
  SELECT
    COUNT(*) OVER() AS total_count,
    l.id AS listing_id,
    l.public_id,
    l.title,
    at.name AS accommodation_type_name,
    l.furnishing,
    l.gender_preference,
    l.occupancy_type,
    l.max_occupants,
    l.locality,
    l.city,
    l.country,
    l.formatted_address,
    lp.amount AS price_amount,
    lp.currency AS price_currency,
    lp.billing_period AS price_billing_period,
    lp.minimum_duration AS price_minimum_duration,
    (
      SELECT li.storage_path
      FROM public.listing_images li
      WHERE li.listing_id = l.id
      ORDER BY li.is_cover DESC, li.display_order ASC
      LIMIT 1
    ) AS image_url
  FROM public.listings l
  JOIN public.accommodation_types at ON at.id = l.accommodation_type_id
  LEFT JOIN public.listing_prices lp ON lp.listing_id = l.id
  WHERE
    -- Only published listings
    l.status = 'published'

    -- Location filters (ILIKE for V1; will move to ID-based in V2)
    AND (p_city IS NULL OR l.city ILIKE p_city)
    AND (p_locality IS NULL OR l.locality ILIKE p_locality)

    -- Accommodation type filter (UUID-based)
    AND (p_accommodation_type_id IS NULL OR l.accommodation_type_id = p_accommodation_type_id)

    -- Property attribute filters
    AND (p_furnishing IS NULL OR l.furnishing = p_furnishing)
    AND (p_gender_preference IS NULL OR l.gender_preference = p_gender_preference)
    AND (p_occupancy_type IS NULL OR l.occupancy_type = p_occupancy_type)

    -- Billing period filter
    AND (p_billing_period IS NULL OR lp.billing_period = p_billing_period)

    -- Price range filters
    AND (p_min_price IS NULL OR lp.amount >= p_min_price)
    AND (p_max_price IS NULL OR lp.amount <= p_max_price)

    -- Availability filter
    AND (
      p_available_from IS NULL
      OR EXISTS (
        SELECT 1 FROM public.listing_availability la
        WHERE la.listing_id = l.id
          AND la.status = 'available'
          AND la.available_from <= p_available_from
      )
    )

    -- Amenities filter: listing must have ALL requested amenities
    AND (
      p_amenities IS NULL
      OR array_length(p_amenities, 1) IS NULL
      OR NOT EXISTS (
        SELECT unnest(p_amenities)
        EXCEPT
        SELECT a.name
        FROM public.listing_amenities la2
        JOIN public.amenities a ON a.id = la2.amenity_id
        WHERE la2.listing_id = l.id
      )
    )

  ORDER BY
    CASE WHEN p_sort = 'price_asc' THEN lp.amount END ASC NULLS LAST,
    CASE WHEN p_sort = 'price_desc' THEN lp.amount END DESC NULLS LAST,
    CASE WHEN p_sort = 'newest' THEN l.created_at END DESC,
    CASE WHEN p_sort = 'recommended' OR p_sort IS NULL THEN l.created_at END DESC

  LIMIT p_page_size
  OFFSET v_offset;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- SOURCE: 16_seed_reference_data.sql
-- Insert Accommodation Types
INSERT INTO public.accommodation_types (id, name, description) VALUES
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'PG', 'Paying Guest accommodation'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'Hostel', 'Shared hostel accommodation'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'Apartment', 'Standard residential apartment'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a14', 'Independent House', 'Standalone house or bungalow'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a15', 'Villa', 'Luxury standalone villa'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a16', 'Private Room', 'Private room within a shared property'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a17', 'Shared Room', 'Shared room with other occupants'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a18', 'Service Apartment', 'Furnished apartment with hotel-like services'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a19', 'Co-living', 'Modern managed shared living spaces');

-- Insert Amenities (Categorized conceptually, stored flat)
-- Essentials
INSERT INTO public.amenities (id, name, icon) VALUES
  ('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b11', 'Wi-Fi', 'wifi'),
  ('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b12', 'Electricity', 'zap'),
  ('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b13', 'Water', 'droplets');
-- Comfort
INSERT INTO public.amenities (id, name, icon) VALUES
  ('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b14', 'AC', 'snowflake'),
  ('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b15', 'Geyser', 'thermometer'),
  ('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b16', 'Refrigerator', 'refrigerator');
-- Services
INSERT INTO public.amenities (id, name, icon) VALUES
  ('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b17', 'Laundry', 'shirt'),
  ('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b18', 'Housekeeping', 'broom'),
  ('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b19', 'Meals', 'utensils');
-- Security
INSERT INTO public.amenities (id, name, icon) VALUES
  ('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b20', 'CCTV', 'camera'),
  ('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b21', 'Security Guard', 'shield'),
  ('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b22', 'Biometric Entry', 'fingerprint');
-- Parking
INSERT INTO public.amenities (id, name, icon) VALUES
  ('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b23', 'Bike Parking', 'bike'),
  ('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b24', 'Car Parking', 'car');

-- Seed Listings
WITH test_host AS (
  SELECT id FROM public.profiles LIMIT 1
)
INSERT INTO public.listings (
  id, host_id, accommodation_type_id, title, description, max_occupants,
  country_code, country, state, city, locality, postal_code, latitude, longitude, formatted_address,
  status, public_id, furnishing, gender_preference, occupancy_type
) VALUES
(
  'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380c11', (SELECT id FROM test_host), 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', -- PG
  'Premium Boys PG in HSR Layout', 'Spacious shared rooms with all amenities included.', 2,
  'IN', 'India', 'Karnataka', 'Bangalore', 'HSR Layout', '560102', 12.9081, 77.6476, 'HSR Layout Sector 2, Bangalore, Karnataka',
  'published', 'lst_pg_hsr', 'fully_furnished', 'male', 'shared'
),
(
  'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380c12', (SELECT id FROM test_host), 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', -- Hostel
  'Girls Hostel - Gachibowli', 'Safe and secure girls hostel near major tech parks.', 3,
  'IN', 'India', 'Telangana', 'Hyderabad', 'Gachibowli', '500032', 17.4401, 78.3489, 'Gachibowli, Hyderabad, Telangana',
  'published', 'lst_hst_gcb', 'fully_furnished', 'female', 'shared'
),
(
  'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380c13', (SELECT id FROM test_host), 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a19', -- Co-living
  'Modern Co-living Space Koramangala', 'Experience community living in the heart of the city.', 1,
  'IN', 'India', 'Karnataka', 'Bangalore', 'Koramangala', '560034', 12.9279, 77.6271, 'Koramangala 5th Block, Bangalore, Karnataka',
  'published', 'lst_col_krm', 'fully_furnished', 'any', 'mixed'
),
(
  'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380c14', (SELECT id FROM test_host), 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', -- Apartment
  '2BHK Apartment in Kondapur', 'Semi-furnished 2BHK perfect for small families.', 4,
  'IN', 'India', 'Telangana', 'Hyderabad', 'Kondapur', '500084', 17.4622, 78.3568, 'Kondapur Main Road, Hyderabad, Telangana',
  'published', 'lst_apt_knd', 'semi_furnished', 'any', 'private'
);

-- Seed Pricing
INSERT INTO public.listing_prices (listing_id, amount, currency, billing_period, minimum_duration, security_deposit, maintenance_fee) VALUES
('c0eebc99-9c0b-4ef8-bb6d-6bb9bd380c11', 12000, 'INR', 'month', 3, 24000, 0), -- PG
('c0eebc99-9c0b-4ef8-bb6d-6bb9bd380c12', 9500, 'INR', 'month', 6, 19000, 0), -- Girls Hostel
('c0eebc99-9c0b-4ef8-bb6d-6bb9bd380c13', 25000, 'INR', 'month', 1, 50000, 1500), -- Co-living
('c0eebc99-9c0b-4ef8-bb6d-6bb9bd380c14', 45000, 'INR', 'month', 11, 135000, 3000); -- Apartment

-- Seed Availability
INSERT INTO public.listing_availability (listing_id, available_from, available_units, status) VALUES
('c0eebc99-9c0b-4ef8-bb6d-6bb9bd380c11', CURRENT_DATE, 5, 'available'),
('c0eebc99-9c0b-4ef8-bb6d-6bb9bd380c12', CURRENT_DATE + INTERVAL '5 days', 12, 'available'),
('c0eebc99-9c0b-4ef8-bb6d-6bb9bd380c13', CURRENT_DATE, 2, 'available'),
('c0eebc99-9c0b-4ef8-bb6d-6bb9bd380c14', CURRENT_DATE + INTERVAL '15 days', 1, 'available');

-- Add Images (Sample Unsplash Links)
INSERT INTO public.listing_images (listing_id, storage_path, display_order) VALUES
('c0eebc99-9c0b-4ef8-bb6d-6bb9bd380c11', 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80', 1),
('c0eebc99-9c0b-4ef8-bb6d-6bb9bd380c12', 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80', 1),
('c0eebc99-9c0b-4ef8-bb6d-6bb9bd380c13', 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80', 1),
('c0eebc99-9c0b-4ef8-bb6d-6bb9bd380c14', 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80', 1);

-- Link Amenities to Listings
-- PG gets Wi-Fi, Water, Electricity, Meals, Bike Parking
INSERT INTO public.listing_amenities (listing_id, amenity_id) VALUES
('c0eebc99-9c0b-4ef8-bb6d-6bb9bd380c11', 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b11'), -- Wifi
('c0eebc99-9c0b-4ef8-bb6d-6bb9bd380c11', 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b12'), -- Electricity
('c0eebc99-9c0b-4ef8-bb6d-6bb9bd380c11', 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b13'), -- Water
('c0eebc99-9c0b-4ef8-bb6d-6bb9bd380c11', 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b19'), -- Meals
('c0eebc99-9c0b-4ef8-bb6d-6bb9bd380c11', 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b23'); -- Bike Parking
-- 20260731050000_rpc_india_first.sql

CREATE OR REPLACE FUNCTION public.get_listing_detail(p_public_id TEXT)
RETURNS JSON AS $$
DECLARE
    result JSON;
BEGIN
    SELECT row_to_json(l_data) INTO result
    FROM (
        SELECT 
            l.id,
            l.public_id,
            l.title,
            l.description,
            l.max_occupants,
            l.status,
            l.furnishing,
            l.gender_preference,
            l.occupancy_type,
            l.created_at,
            l.country_code,
            l.country,
            l.state,
            l.city,
            l.locality,
            l.postal_code,
            l.latitude,
            l.longitude,
            l.formatted_address,
            (
                SELECT row_to_json(t)
                FROM (
                    SELECT name, description
                    FROM public.accommodation_types
                    WHERE id = l.accommodation_type_id
                ) t
            ) as accommodation_type,
            (
                SELECT row_to_json(h)
                FROM (
                    SELECT 
                        p.id,
                        p.full_name,
                        p.avatar_url,
                        p.created_at
                    FROM public.profiles p
                    WHERE p.id = l.host_id
                ) h
            ) as host,
            (
                SELECT row_to_json(pr)
                FROM (
                    SELECT 
                        amount,
                        currency,
                        billing_period,
                        security_deposit,
                        maintenance_fee,
                        maintenance_fee_period,
                        minimum_duration,
                        maximum_duration
                    FROM public.listing_prices
                    WHERE listing_id = l.id
                ) pr
            ) as pricing,
            (
                SELECT row_to_json(av)
                FROM (
                    SELECT 
                        available_from,
                        available_units,
                        status
                    FROM public.listing_availability
                    WHERE listing_id = l.id
                ) av
            ) as availability,
            (
                SELECT COALESCE(json_agg(row_to_json(img)), '[]'::json)
                FROM (
                    SELECT 
                        storage_path as image_url,
                        display_order
                    FROM public.listing_images
                    WHERE listing_id = l.id
                    ORDER BY display_order ASC
                ) img
            ) as images,
            (
                SELECT COALESCE(json_agg(row_to_json(am)), '[]'::json)
                FROM (
                    SELECT 
                        a.name,
                        a.icon
                    FROM public.listing_amenities la
                    JOIN public.amenities a ON a.id = la.amenity_id
                    WHERE la.listing_id = l.id
                ) am
            ) as amenities
        FROM public.listings l
        WHERE l.public_id = p_public_id
        AND (
            l.status = 'published' 
            OR public.is_listing_owner(l.id) 
            OR public.is_admin()
        )
    ) l_data;

    RETURN result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
-- 20260731060000_maintenance_fee_and_buckets.sql

-- 1. Add maintenance_fee_period to listing_prices
-- First we add the column using the existing billing_period enum.
-- We also add a default value to not break existing rows, then we can drop the default if we want, but it's fine to keep it.
ALTER TABLE public.listing_prices 
ADD COLUMN IF NOT EXISTS maintenance_fee_period billing_period DEFAULT 'semester'::billing_period;

-- 2. Create Storage Buckets with strict size limits
-- listings: max 2MB


