/*
==================================================
Migration: Phase 3 Listing Semantics & Reference Data Governance (10/10 Architecture)
Purpose:
  1. Enforce standard Reference Data Governance across property_types, accommodation_types, and amenities (slug, icon, display_order, is_active, description).
  2. Create facing_directions reference lookup table for orientation and Vaastu filtering.
  3. Create listing_features 1-to-1 child table (physical characteristics like balcony_count, floor, orientation, and unit-agnostic area).
  4. Create listing_rules 1-to-1 child table (operational policies tailored to Indian co-living with paired interval checks).
  5. Create listing_rule_notes child table for editable, ordered custom house policies.
  6. Establish inherited RLS policies across all new listing semantics tables.
==================================================
*/

-- 1. Reference Data Governance Alignment
-- 1.1 property_types
ALTER TABLE public.property_types
    ADD COLUMN IF NOT EXISTS slug TEXT;

UPDATE public.property_types 
SET slug = LOWER(REPLACE(name, ' ', '-')) 
WHERE slug IS NULL;

ALTER TABLE public.property_types 
    ALTER COLUMN slug SET NOT NULL,
    ADD CONSTRAINT uk_property_types_slug UNIQUE (slug);

-- 1.2 accommodation_types
ALTER TABLE public.accommodation_types
    ADD COLUMN IF NOT EXISTS slug TEXT,
    ADD COLUMN IF NOT EXISTS icon TEXT,
    ADD COLUMN IF NOT EXISTS display_order INTEGER DEFAULT 0 NOT NULL,
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true NOT NULL;

UPDATE public.accommodation_types
SET 
    slug = LOWER(REPLACE(name, ' ', '-')),
    display_order = CASE 
        WHEN name = 'PG' THEN 10
        WHEN name = 'Hostel' THEN 20
        WHEN name = 'Co-living' THEN 30
        WHEN name = 'Apartment' THEN 40
        WHEN name = 'Independent House' THEN 50
        WHEN name = 'Villa' THEN 60
        WHEN name = 'Private Room' THEN 70
        WHEN name = 'Shared Room' THEN 80
        WHEN name = 'Service Apartment' THEN 90
        ELSE 100 
    END,
    icon = CASE
        WHEN name = 'PG' THEN 'users'
        WHEN name = 'Hostel' THEN 'building'
        WHEN name = 'Co-living' THEN 'share-2'
        WHEN name = 'Apartment' THEN 'home'
        WHEN name = 'Independent House' THEN 'house'
        WHEN name = 'Villa' THEN 'castle'
        ELSE 'home'
    END
WHERE slug IS NULL OR display_order = 0;

ALTER TABLE public.accommodation_types 
    ALTER COLUMN slug SET NOT NULL,
    ADD CONSTRAINT uk_accommodation_types_slug UNIQUE (slug);

-- 1.3 amenities
ALTER TABLE public.amenities
    ADD COLUMN IF NOT EXISTS slug TEXT,
    ADD COLUMN IF NOT EXISTS description TEXT,
    ADD COLUMN IF NOT EXISTS display_order INTEGER DEFAULT 0 NOT NULL,
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true NOT NULL;

UPDATE public.amenities 
SET slug = LOWER(REPLACE(REPLACE(name, ' ', '-'), '/', '-')) 
WHERE slug IS NULL;

ALTER TABLE public.amenities 
    ALTER COLUMN slug SET NOT NULL,
    ADD CONSTRAINT uk_amenities_slug UNIQUE (slug);


-- 2. Create facing_directions Reference Table
CREATE TABLE IF NOT EXISTS public.facing_directions (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    description TEXT,
    icon TEXT,
    display_order INTEGER DEFAULT 0 NOT NULL,
    is_active BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

ALTER TABLE public.facing_directions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access on facing_directions" ON public.facing_directions;
CREATE POLICY "Allow public read access on facing_directions"
    ON public.facing_directions FOR SELECT
    USING (is_active = true OR public.is_admin());

DROP POLICY IF EXISTS "Allow admin management on facing_directions" ON public.facing_directions;
CREATE POLICY "Allow admin management on facing_directions"
    ON public.facing_directions FOR ALL
    USING (public.is_admin());

DROP TRIGGER IF EXISTS trigger_facing_directions_updated_at ON public.facing_directions;
CREATE OR REPLACE TRIGGER trigger_facing_directions_updated_at
    BEFORE UPDATE ON public.facing_directions
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

INSERT INTO public.facing_directions (id, name, slug, description, icon, display_order) VALUES
    (1, 'North', 'north', 'North-facing orientation', 'compass', 10),
    (2, 'North-East', 'north-east', 'North-East orientation (Auspicious in Vaastu)', 'compass', 20),
    (3, 'East', 'east', 'East-facing morning sun orientation', 'compass', 30),
    (4, 'South-East', 'south-east', 'South-East orientation', 'compass', 40),
    (5, 'South', 'south', 'South-facing orientation', 'compass', 50),
    (6, 'South-West', 'south-west', 'South-West orientation', 'compass', 60),
    (7, 'West', 'west', 'West-facing evening sunlight orientation', 'compass', 70),
    (8, 'North-West', 'north-west', 'North-West orientation', 'compass', 80)
ON CONFLICT (id) DO UPDATE 
SET name = EXCLUDED.name, slug = EXCLUDED.slug, description = EXCLUDED.description, icon = EXCLUDED.icon, display_order = EXCLUDED.display_order;


-- 3. Create listing_features Table (Physical Characteristics)
CREATE TABLE IF NOT EXISTS public.listing_features (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    listing_id UUID NOT NULL UNIQUE REFERENCES public.listings(id) ON DELETE CASCADE,
    floor_number INTEGER,
    total_floors INTEGER,
    area NUMERIC,
    area_unit VARCHAR(20) DEFAULT 'sqft' NOT NULL,
    facing_direction_id SMALLINT REFERENCES public.facing_directions(id),
    balcony_count SMALLINT DEFAULT 0 NOT NULL,
    has_lift BOOLEAN DEFAULT false NOT NULL,
    has_attached_bathroom BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    CONSTRAINT check_balcony_count CHECK (balcony_count >= 0),
    CONSTRAINT check_area CHECK (area IS NULL OR area > 0),
    CONSTRAINT check_area_unit CHECK (area_unit IN ('sqft', 'sqm', 'sqyd', 'acre', 'hectare'))
);

CREATE INDEX IF NOT EXISTS idx_listing_features_listing_id ON public.listing_features(listing_id);
CREATE INDEX IF NOT EXISTS idx_listing_features_facing_direction_id ON public.listing_features(facing_direction_id);

ALTER TABLE public.listing_features ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow read access inherited from listings on features" ON public.listing_features;
CREATE POLICY "Allow read access inherited from listings on features"
    ON public.listing_features FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.listings l
            WHERE l.id = listing_features.listing_id
              AND (l.status = 'published' OR public.is_listing_owner(l.id) OR public.is_admin())
        )
    );

DROP POLICY IF EXISTS "Allow owners to manage listing features" ON public.listing_features;
CREATE POLICY "Allow owners to manage listing features"
    ON public.listing_features FOR ALL
    USING (public.is_listing_owner(listing_id) OR public.is_admin())
    WITH CHECK (public.is_listing_owner(listing_id) OR public.is_admin());

DROP TRIGGER IF EXISTS trigger_listing_features_updated_at ON public.listing_features;
CREATE OR REPLACE TRIGGER trigger_listing_features_updated_at
    BEFORE UPDATE ON public.listing_features
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();


-- 4. Create listing_rules Table (Operational Policies)
CREATE TABLE IF NOT EXISTS public.listing_rules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    listing_id UUID NOT NULL UNIQUE REFERENCES public.listings(id) ON DELETE CASCADE,
    smoking_allowed BOOLEAN DEFAULT false NOT NULL,
    pets_allowed BOOLEAN DEFAULT false NOT NULL,
    visitors_allowed BOOLEAN DEFAULT true NOT NULL,
    couples_allowed BOOLEAN DEFAULT true NOT NULL,
    non_vegetarian_allowed BOOLEAN DEFAULT true NOT NULL,
    parties_allowed BOOLEAN DEFAULT false NOT NULL,
    quiet_hours_start TIME,
    quiet_hours_end TIME,
    gate_closing_time TIME,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    CONSTRAINT check_quiet_hours_pair CHECK (
        (quiet_hours_start IS NULL AND quiet_hours_end IS NULL) OR 
        (quiet_hours_start IS NOT NULL AND quiet_hours_end IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_listing_rules_listing_id ON public.listing_rules(listing_id);

ALTER TABLE public.listing_rules ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow read access inherited from listings on rules" ON public.listing_rules;
CREATE POLICY "Allow read access inherited from listings on rules"
    ON public.listing_rules FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.listings l
            WHERE l.id = listing_rules.listing_id
              AND (l.status = 'published' OR public.is_listing_owner(l.id) OR public.is_admin())
        )
    );

DROP POLICY IF EXISTS "Allow owners to manage listing rules" ON public.listing_rules;
CREATE POLICY "Allow owners to manage listing rules"
    ON public.listing_rules FOR ALL
    USING (public.is_listing_owner(listing_id) OR public.is_admin())
    WITH CHECK (public.is_listing_owner(listing_id) OR public.is_admin());

DROP TRIGGER IF EXISTS trigger_listing_rules_updated_at ON public.listing_rules;
CREATE OR REPLACE TRIGGER trigger_listing_rules_updated_at
    BEFORE UPDATE ON public.listing_rules
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();


-- 5. Create listing_rule_notes Table (Normalized Rule Notes)
CREATE TABLE IF NOT EXISTS public.listing_rule_notes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    listing_id UUID NOT NULL REFERENCES public.listings(id) ON DELETE CASCADE,
    rule_text TEXT NOT NULL,
    display_order INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_listing_rule_notes_listing_id ON public.listing_rule_notes(listing_id, display_order);

ALTER TABLE public.listing_rule_notes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow read access inherited from listings on rule notes" ON public.listing_rule_notes;
CREATE POLICY "Allow read access inherited from listings on rule notes"
    ON public.listing_rule_notes FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.listings l
            WHERE l.id = listing_rule_notes.listing_id
              AND (l.status = 'published' OR public.is_listing_owner(l.id) OR public.is_admin())
        )
    );

DROP POLICY IF EXISTS "Allow owners to manage listing rule notes" ON public.listing_rule_notes;
CREATE POLICY "Allow owners to manage listing rule notes"
    ON public.listing_rule_notes FOR ALL
    USING (public.is_listing_owner(listing_id) OR public.is_admin())
    WITH CHECK (public.is_listing_owner(listing_id) OR public.is_admin());

DROP TRIGGER IF EXISTS trigger_listing_rule_notes_updated_at ON public.listing_rule_notes;
CREATE OR REPLACE TRIGGER trigger_listing_rule_notes_updated_at
    BEFORE UPDATE ON public.listing_rule_notes
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
