-- Populate comprehensive descriptive explanations for all 42 reference amenities
UPDATE public.amenities SET description = 'Individual air conditioning unit for temperature-controlled comfort' WHERE slug = 'ac';
UPDATE public.amenities SET description = 'Centralized or individual air conditioning system throughout the living spaces' WHERE slug = 'air-conditioning';
UPDATE public.amenities SET description = 'Private open-air balcony offering natural light and outdoor seating' WHERE slug = 'balcony';
UPDATE public.amenities SET description = 'Designated outdoor barbecue cooking area for social gatherings' WHERE slug = 'bbq-area';
UPDATE public.amenities SET description = 'Sturdy bed frame equipped with a comfortable, quality mattress' WHERE slug = 'bed';
UPDATE public.amenities SET description = 'Secure on-site covered two-wheeler parking' WHERE slug = 'bike-parking';
UPDATE public.amenities SET description = 'Keyless fingerprint or smart biometric access for enhanced resident security' WHERE slug = 'biometric-entry';
UPDATE public.amenities SET description = 'Designated parking slot for cars within the gated premises' WHERE slug = 'car-parking';
UPDATE public.amenities SET description = '24/7 common area video surveillance monitoring for resident safety' WHERE slug = 'cctv';
UPDATE public.amenities SET description = 'Shared community lounge for socializing, reading, and relaxing' WHERE slug = 'common-room';
UPDATE public.amenities SET description = 'Reliable 24-hour grid electrical connection included or sub-metered' WHERE slug = 'electricity';
UPDATE public.amenities SET description = 'Integrated smoke detectors and emergency fire alert system' WHERE slug = 'fire-alarm';
UPDATE public.amenities SET description = 'Lush landscaped green garden area on the property ground' WHERE slug = 'garden';
UPDATE public.amenities SET description = 'Cooking cooktop with secure gas connection for daily meal prep' WHERE slug = 'gas-stove';
UPDATE public.amenities SET description = 'Instant electric or solar water heater for warm showers at any time' WHERE slug = 'geyser';
UPDATE public.amenities SET description = 'On-site fitness facility equipped with free weights and workout cardio machines' WHERE slug = 'gym';
UPDATE public.amenities SET description = 'Professional room cleaning and common facility housekeeping service' WHERE slug = 'housekeeping';
UPDATE public.amenities SET description = 'Access to a well-equipped shared or private cooking kitchen' WHERE slug = 'kitchen';
UPDATE public.amenities SET description = 'Washing machines and drying amenities available on-site for daily laundry' WHERE slug = 'laundry';
UPDATE public.amenities SET description = 'Modern building elevator providing step-free access to all floor levels' WHERE slug = 'lift';
UPDATE public.amenities SET description = 'Personal secure lockable storage compartments for valuables' WHERE slug = 'lockers';
UPDATE public.amenities SET description = 'Nutritious daily breakfast, lunch, and dinner meal service included or optional' WHERE slug = 'meals';
UPDATE public.amenities SET description = 'Dedicated communal dining hall served with prepared home-style food' WHERE slug = 'mess';
UPDATE public.amenities SET description = 'Shared or private microwave appliance for quick reheating and cooking' WHERE slug = 'microwave';
UPDATE public.amenities SET description = 'Safe residential vehicular parking available on or directly beside property' WHERE slug = 'parking';
UPDATE public.amenities SET description = 'Accommodates well-behaved companion domestic pets' WHERE slug = 'pet-friendly';
UPDATE public.amenities SET description = 'Relaxing recreational swimming pool accessible to community residents' WHERE slug = 'pool';
UPDATE public.amenities SET description = 'Uninterrupted generator or inverter backup power during grid outages' WHERE slug = 'power-backup';
UPDATE public.amenities SET description = 'Dedicated personal parking space reserved exclusively for this listing' WHERE slug = 'private-parking';
UPDATE public.amenities SET description = 'On-site help desk or front desk concierge for mail and visitor support' WHERE slug = 'reception';
UPDATE public.amenities SET description = 'Cold storage food preservation refrigerator provided in kitchen or room' WHERE slug = 'refrigerator';
UPDATE public.amenities SET description = 'Filtered Reverse Osmosis drinking water purified on location' WHERE slug = 'ro-water';
UPDATE public.amenities SET description = 'Gated premises featuring rigorous security measures and monitored ingress' WHERE slug = 'security';
UPDATE public.amenities SET description = 'Trained physical security personnel patrolling the property around the clock' WHERE slug = 'security-guard';
UPDATE public.amenities SET description = 'Quiet dedicated co-working and study atmosphere with adequate reading lighting' WHERE slug = 'study-area';
UPDATE public.amenities SET description = 'Private work desk and ergonomic study chair furnished inside the bedroom' WHERE slug = 'study-table';
UPDATE public.amenities SET description = 'Open rooftop communal terrace overlooking neighborhood surroundings' WHERE slug = 'terrace';
UPDATE public.amenities SET description = 'Spacious storage cupboard or closet with clothes hanging rail and shelving' WHERE slug = 'wardrobe';
UPDATE public.amenities SET description = 'Dependable around-the-clock municipal or borewell utility water supply' WHERE slug = 'water';
UPDATE public.amenities SET description = 'Step-free level access ramps and widened doorways for mobility support' WHERE slug = 'wheelchair-access';
UPDATE public.amenities SET description = 'High-speed wireless internet broadband connectivity for work and entertainment' WHERE slug = 'wi-fi';
UPDATE public.amenities SET description = 'Fast wireless internet coverage across individual rooms and shared facilities' WHERE slug = 'wifi';
