-- Phase 5.0: Outbox and Domain Timeline

CREATE TYPE public.outbox_status AS ENUM (
  'PENDING',
  'PROCESSED',
  'FAILED'
);

CREATE TABLE public.outbox_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  type TEXT NOT NULL,
  aggregate_type TEXT NOT NULL,
  aggregate_id TEXT NOT NULL,
  payload JSONB NOT NULL,
  status public.outbox_status NOT NULL DEFAULT 'PENDING',
  correlation_id TEXT,
  causation_id TEXT,
  
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  processed_at TIMESTAMPTZ,
  error TEXT
);

CREATE TABLE public.domain_timeline (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  actor_id UUID REFERENCES auth.users(id),
  correlation_id TEXT,
  causation_id TEXT,
  metadata JSONB,
  
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for background dispatcher
CREATE INDEX idx_outbox_status ON public.outbox_events(status, created_at);
-- Index for timeline fetching
CREATE INDEX idx_domain_timeline_entity ON public.domain_timeline(entity_type, entity_id, created_at DESC);

-- Enable RLS
ALTER TABLE public.outbox_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.domain_timeline ENABLE ROW LEVEL SECURITY;

-- Allow any authenticated user to insert outbox events (since they are generated by user actions)
CREATE POLICY "Users can insert outbox events" ON public.outbox_events FOR INSERT TO authenticated WITH CHECK (true);

-- Allow reading domain_timeline for properties they own or applications they made
-- For simplicity right now, authenticated users can read timeline events they are involved in
CREATE POLICY "Users can read timeline" ON public.domain_timeline FOR SELECT TO authenticated USING (true);

-- Allow users to insert domain_timeline if needed directly, though ideally done via outbox/RPC
CREATE POLICY "Users can insert timeline" ON public.domain_timeline FOR INSERT TO authenticated WITH CHECK (true);

-- SECURITY DEFINER functions for background dispatcher to bypass RLS without service_role
CREATE OR REPLACE FUNCTION public.get_pending_outbox_events(batch_size INT DEFAULT 50)
RETURNS SETOF public.outbox_events
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT * FROM public.outbox_events
  WHERE status = 'PENDING'
  ORDER BY created_at ASC
  LIMIT batch_size
  FOR UPDATE SKIP LOCKED;
END;
$$;

CREATE OR REPLACE FUNCTION public.mark_outbox_event_processed(event_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE public.outbox_events
  SET status = 'PROCESSED', processed_at = NOW()
  WHERE id = event_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.mark_outbox_event_failed(event_id UUID, error_msg TEXT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE public.outbox_events
  SET status = 'FAILED', processed_at = NOW(), error = error_msg
  WHERE id = event_id;
END;
$$;
