/*
==================================================
Migration: Phase 2 Amenity Normalization & Locality Enrichment (10/10 Architecture)
Purpose:
  1. Enrich localities with display_name, aliases array, search_rank, and optional population.
  2. Create amenity_categories reference table (SMALLINT PK) with domain-specific categories, icons, and slugs.
  3. Alter amenities table to add category_id FK, is_filterable, is_featured flag, and search_weight.
  4. Backfill existing amenities via an explicit, resilient inline mapping table expression.
==================================================
*/

-- 1. Enrich Localities Table
ALTER TABLE public.localities
    ADD COLUMN IF NOT EXISTS display_name TEXT,
    ADD COLUMN IF NOT EXISTS aliases TEXT[] DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS search_rank INTEGER DEFAULT 0 NOT NULL,
    ADD COLUMN IF NOT EXISTS population INTEGER;

-- Comment on search_rank values for standard repository understanding
COMMENT ON COLUMN public.localities.search_rank IS 'Weighting for discovery and autocomplete: 1000 = Tier-1 locality, 500 = Very popular, 100 = Normal locality, 10 = Rare locality';

CREATE INDEX IF NOT EXISTS idx_localities_search_rank ON public.localities(search_rank DESC);


-- 2. Create amenity_categories Reference Table
CREATE TABLE IF NOT EXISTS public.amenity_categories (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    description TEXT,
    icon TEXT,
    display_order INTEGER DEFAULT 0 NOT NULL,
    is_active BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

ALTER TABLE public.amenity_categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access on amenity_categories" ON public.amenity_categories;
CREATE POLICY "Allow public read access on amenity_categories"
    ON public.amenity_categories
    FOR SELECT
    USING (is_active = true OR public.is_admin());

DROP POLICY IF EXISTS "Allow admin management on amenity_categories" ON public.amenity_categories;
CREATE POLICY "Allow admin management on amenity_categories"
    ON public.amenity_categories
    FOR ALL
    USING (public.is_admin());

DROP TRIGGER IF EXISTS trigger_amenity_categories_updated_at ON public.amenity_categories;
CREATE OR REPLACE TRIGGER trigger_amenity_categories_updated_at
    BEFORE UPDATE ON public.amenity_categories
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- Seed initial domain-specific amenity categories
INSERT INTO public.amenity_categories (id, name, slug, description, icon, display_order)
VALUES
    (1, 'Internet & Connectivity', 'internet-connectivity', 'High-speed internet and digital communications', 'wifi', 10),
    (2, 'Utilities', 'utilities', 'Essential property power and water supplies', 'zap', 20),
    (3, 'Kitchen & Dining', 'kitchen-dining', 'Cooking appliances, refrigeration, and dining furnishings', 'utensils', 30),
    (4, 'Bedroom & Comfort', 'bedroom-comfort', 'Climate control and bedding comforts', 'bed', 40),
    (5, 'Bathroom & Hygiene', 'bathroom-hygiene', 'Sanitation, hot water geysers, and hygiene fixtures', 'shower', 50),
    (6, 'Safety & Security', 'safety-security', 'Property surveillance, access systems, and guards', 'shield', 60),
    (7, 'Parking & Transit', 'parking-transit', 'Dedicated vehicular parking facilities', 'car', 70),
    (8, 'Laundry & Housekeeping', 'laundry-housekeeping', 'Clothing cleaning and scheduled room maintenance', 'shirt', 80),
    (9, 'Recreation & Wellness', 'recreation-wellness', 'Fitness centers, swimming pools, and recreation', 'dumbbell', 90),
    (10, 'Outdoor & Common Spaces', 'outdoor-common-spaces', 'Shared communal lounges, balconies, and lawns', 'sun', 100),
    (11, 'Services & Managed Care', 'services-managed-care', 'Prepared meals and concierge living assistance', 'concierge-bell', 110)
ON CONFLICT (id) DO UPDATE 
SET name = EXCLUDED.name, slug = EXCLUDED.slug, description = EXCLUDED.description, icon = EXCLUDED.icon, display_order = EXCLUDED.display_order;


-- 3. Alter amenities to reference category, filterability, card UI prominence, and search weighting
ALTER TABLE public.amenities
    ADD COLUMN IF NOT EXISTS category_id SMALLINT REFERENCES public.amenity_categories(id),
    ADD COLUMN IF NOT EXISTS is_filterable BOOLEAN DEFAULT true NOT NULL,
    ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT false NOT NULL,
    ADD COLUMN IF NOT EXISTS search_weight INTEGER DEFAULT 50 NOT NULL;

CREATE INDEX IF NOT EXISTS idx_amenities_category_id ON public.amenities(category_id);
CREATE INDEX IF NOT EXISTS idx_amenities_is_filterable ON public.amenities(is_filterable);
CREATE INDEX IF NOT EXISTS idx_amenities_is_featured ON public.amenities(is_featured);
CREATE INDEX IF NOT EXISTS idx_amenities_search_weight ON public.amenities(search_weight DESC);


-- 4. Backfill existing amenity mappings using a structured mapping expression
WITH amenity_mapping (name_pattern, category_slug, filterable, featured, weight) AS (
    VALUES
        ('wi-fi', 'internet-connectivity', true, true, 100),
        ('wifi', 'internet-connectivity', true, true, 100),
        ('electricity', 'utilities', true, true, 80),
        ('water', 'utilities', true, false, 80),
        ('ac', 'bedroom-comfort', true, true, 90),
        ('air conditioning', 'bedroom-comfort', true, true, 90),
        ('geyser', 'bathroom-hygiene', true, false, 80),
        ('refrigerator', 'kitchen-dining', true, false, 70),
        ('kitchen', 'kitchen-dining', true, true, 95),
        ('laundry', 'laundry-housekeeping', true, false, 75),
        ('housekeeping', 'laundry-housekeeping', true, false, 75),
        ('meals', 'services-managed-care', true, true, 85),
        ('cctv', 'safety-security', true, false, 80),
        ('security guard', 'safety-security', true, false, 85),
        ('biometric entry', 'safety-security', false, false, 50),
        ('bike parking', 'parking-transit', true, false, 70),
        ('car parking', 'parking-transit', true, true, 85),
        ('parking', 'parking-transit', true, true, 85),
        ('pool', 'recreation-wellness', true, false, 60),
        ('gym', 'recreation-wellness', true, false, 70),
        ('balcony', 'outdoor-common-spaces', true, false, 75),
        ('bbq area', 'outdoor-common-spaces', false, false, 50),
        ('bed', 'bedroom-comfort', true, false, 70),
        ('common room', 'outdoor-common-spaces', false, false, 60),
        ('fire alarm', 'safety-security', false, false, 75),
        ('garden', 'outdoor-common-spaces', true, false, 70),
        ('gas stove', 'kitchen-dining', false, false, 65),
        ('lift', 'utilities', true, false, 80),
        ('lockers', 'safety-security', false, false, 60),
        ('mess', 'services-managed-care', true, false, 75),
        ('microwave', 'kitchen-dining', true, false, 70),
        ('pet friendly', 'services-managed-care', true, false, 75),
        ('power backup', 'utilities', true, true, 90),
        ('private parking', 'parking-transit', true, true, 85),
        ('reception', 'services-managed-care', false, false, 60),
        ('ro water', 'kitchen-dining', true, false, 75),
        ('security', 'safety-security', true, false, 80),
        ('study area', 'bedroom-comfort', false, false, 65),
        ('study table', 'bedroom-comfort', true, false, 65),
        ('terrace', 'outdoor-common-spaces', true, false, 70),
        ('wardrobe', 'bedroom-comfort', true, false, 70),
        ('wheelchair access', 'utilities', true, false, 75)
)
UPDATE public.amenities a
SET 
    category_id = COALESCE(
        (SELECT ac.id FROM public.amenity_categories ac 
         JOIN amenity_mapping am ON ac.slug = am.category_slug 
         WHERE LOWER(a.name) = am.name_pattern LIMIT 1),
        (SELECT id FROM public.amenity_categories WHERE slug = 'utilities' LIMIT 1)
    ),
    is_filterable = COALESCE(
        (SELECT am.filterable FROM amenity_mapping am WHERE LOWER(a.name) = am.name_pattern LIMIT 1),
        true
    ),
    is_featured = COALESCE(
        (SELECT am.featured FROM amenity_mapping am WHERE LOWER(a.name) = am.name_pattern LIMIT 1),
        false
    ),
    search_weight = COALESCE(
        (SELECT am.weight FROM amenity_mapping am WHERE LOWER(a.name) = am.name_pattern LIMIT 1),
        50
    )
WHERE category_id IS NULL OR search_weight = 50;
