/*
==================================================
Migration: Phase 1 Domain Evolution (9.8/10 Architecture)
Purpose:
  1. Normalize property_types as a SMALLINT reference table & seed initial catalog.
  2. Introduce localities table as a geographic entity under cities with unique constraints.
  3. Alter listings to add property_type_id and locality_id FK columns & backfill data.
  4. Extract listing_capacity into a dedicated table with inherited RLS & backfill from max_occupants.
==================================================
*/

-- 1. Create property_types reference table
CREATE TABLE IF NOT EXISTS public.property_types (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    description TEXT,
    icon TEXT,
    display_order INTEGER DEFAULT 0 NOT NULL,
    is_active BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

ALTER TABLE public.property_types ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access on property_types" ON public.property_types;
CREATE POLICY "Allow public read access on property_types"
    ON public.property_types
    FOR SELECT
    USING (is_active = true OR public.is_admin());

DROP POLICY IF EXISTS "Allow admin management on property_types" ON public.property_types;
CREATE POLICY "Allow admin management on property_types"
    ON public.property_types
    FOR ALL
    USING (public.is_admin());

DROP TRIGGER IF EXISTS trigger_property_types_updated_at ON public.property_types;
CREATE OR REPLACE TRIGGER trigger_property_types_updated_at
    BEFORE UPDATE ON public.property_types
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- Seed initial property_types catalog
INSERT INTO public.property_types (id, name, description, display_order)
VALUES
    (1, 'Apartment', 'Independent residential apartment or flat', 1),
    (2, 'Villa', 'Private villa or upscale independent residence', 2),
    (3, 'House', 'Independent residential house or bungalow', 3),
    (4, 'PG', 'Paying guest accommodation with shared amenities', 4),
    (5, 'Hostel', 'Student or youth hostel dormitory and living spaces', 5),
    (6, 'Hotel', 'Serviced room inside a hospitality establishment', 6),
    (7, 'Cabin', 'Private cabin or standalone natural retreat', 7),
    (8, 'Dormitory', 'Shared sleeping quarters with common living spaces', 8),
    (9, 'Resort', 'Recreational residential resort suite', 9),
    (10, 'Farmhouse', 'Spacious agricultural estate or weekend farmhouse', 10)
ON CONFLICT (id) DO NOTHING;


-- 2. Create localities geographic entity
CREATE TABLE IF NOT EXISTS public.localities (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    city_id BIGINT NOT NULL REFERENCES public.cities(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    slug TEXT NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    is_active BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    CONSTRAINT localities_city_slug_key UNIQUE (city_id, slug),
    CONSTRAINT localities_city_name_key UNIQUE (city_id, name),
    CONSTRAINT check_localities_latitude CHECK (latitude >= -90 AND latitude <= 90),
    CONSTRAINT check_localities_longitude CHECK (longitude >= -180 AND longitude <= 180)
);

CREATE INDEX IF NOT EXISTS idx_localities_city_id ON public.localities(city_id);
CREATE INDEX IF NOT EXISTS idx_localities_slug ON public.localities(slug);
CREATE INDEX IF NOT EXISTS idx_localities_name_lower ON public.localities(LOWER(name));

ALTER TABLE public.localities ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access on localities" ON public.localities;
CREATE POLICY "Allow public read access on localities"
    ON public.localities
    FOR SELECT
    USING (is_active = true OR public.is_admin());

DROP POLICY IF EXISTS "Allow admin management on localities" ON public.localities;
CREATE POLICY "Allow admin management on localities"
    ON public.localities
    FOR ALL
    USING (public.is_admin());

DROP TRIGGER IF EXISTS trigger_localities_updated_at ON public.localities;
CREATE OR REPLACE TRIGGER trigger_localities_updated_at
    BEFORE UPDATE ON public.localities
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();


-- 3. Alter listings to reference normalized entities
ALTER TABLE public.listings 
    ADD COLUMN IF NOT EXISTS property_type_id SMALLINT REFERENCES public.property_types(id),
    ADD COLUMN IF NOT EXISTS locality_id BIGINT REFERENCES public.localities(id);

CREATE INDEX IF NOT EXISTS idx_listings_property_type_id ON public.listings(property_type_id);
CREATE INDEX IF NOT EXISTS idx_listings_locality_id ON public.listings(locality_id);

-- Backfill property_type_id on listings based on existing text values
UPDATE public.listings l
SET property_type_id = COALESCE(
    (SELECT id FROM public.property_types pt WHERE LOWER(pt.name) = LOWER(l.property_type) LIMIT 1),
    1
)
WHERE property_type_id IS NULL;


-- 4. Create listing_capacity table with inherited RLS
CREATE TABLE IF NOT EXISTS public.listing_capacity (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    listing_id UUID NOT NULL UNIQUE REFERENCES public.listings(id) ON DELETE CASCADE,
    beds INTEGER DEFAULT 1 NOT NULL,
    bathrooms INTEGER DEFAULT 1 NOT NULL,
    max_guests INTEGER DEFAULT 1 NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    CONSTRAINT check_capacity_counts CHECK (beds > 0 AND bathrooms > 0 AND max_guests > 0)
);

CREATE INDEX IF NOT EXISTS idx_listing_capacity_listing_id ON public.listing_capacity(listing_id);

ALTER TABLE public.listing_capacity ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow read access inherited from listings" ON public.listing_capacity;
CREATE POLICY "Allow read access inherited from listings"
    ON public.listing_capacity
    FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.listings l
            WHERE l.id = listing_capacity.listing_id
              AND (l.status = 'published' OR public.is_listing_owner(l.id) OR public.is_admin())
        )
    );

DROP POLICY IF EXISTS "Allow listing owners to manage capacity" ON public.listing_capacity;
CREATE POLICY "Allow listing owners to manage capacity"
    ON public.listing_capacity
    FOR ALL
    USING (public.is_listing_owner(listing_id) OR public.is_admin())
    WITH CHECK (public.is_listing_owner(listing_id) OR public.is_admin());

DROP TRIGGER IF EXISTS trigger_listing_capacity_updated_at ON public.listing_capacity;
CREATE OR REPLACE TRIGGER trigger_listing_capacity_updated_at
    BEFORE UPDATE ON public.listing_capacity
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- Backfill listing_capacity from existing listings.max_occupants
INSERT INTO public.listing_capacity (listing_id, max_guests, beds, bathrooms)
SELECT id, COALESCE(max_occupants, 1), 1, 1
FROM public.listings
ON CONFLICT (listing_id) DO UPDATE 
SET max_guests = EXCLUDED.max_guests;
